### ISSUE TITLE
Error in label v8

### ISSUE THREAD

**Issue by CAGIGAL-Computer** [JayVora-SerpentCS/SerpentCS_Contributions-v8#101]
Hi I´ve installed the label module in Odoo v8, it seems everything is fine, and the module is installed successfully.

I´ve created a new label for Partners with Name, City and ZIP, but when i run it from the Partners form, the system opens a new tab with one 400 Bad Request Error:

![image](https://cloud.githubusercontent.com/assets/24866160/26147232/2ddf91a4-3af3-11e7-9cc7-ae7e0e80bb17.png)

The python libs cairosvg, pybarcode and utils are installed.

Thanks and great module

**Comment by hpatelserpentcs** [comment]
@CAGIGAL-Computer 

We have check out label module as per your description created Label for partner and print labels but we did not get any error. If may be error occur in another module.

Thank you.

**Comment by CAGIGAL-Computer** [comment]
I´ve revised the Odoo instance and there was one module `smile_report` that was making any type of problem.

Thanks and sorry for the inconvenience.
