### ISSUE TITLE
Changing the alignment and position of the label

### ISSUE THREAD

**Issue by CAGIGAL-Computer** [JayVora-SerpentCS/SerpentCS_Contributions-v8#104]
Hi, one question: ¿ How can we set the position of the fields in the label, not at the left of the line as it is by default ?

For example, we´d need one label that has 3 lines, with one margin of 2 cm from left of the label

Thanks in advance

**Comment by JayVora-SerpentCS** [comment]
we will chk soon.

**Comment by YogendrasinhChavda** [comment]
Hello @CAGIGAL-Computer 
Can you please tell us which version you are using now? means odoo v10, v9, v8.

**Comment by YogendrasinhChavda** [comment]
Hello @CAGIGAL-Computer 

As per module (Mass Label Reporting) functionality in odoo v10, you have to select the position of the field only in image and barcode " type ".
when you configure the field as a normal type, by default it will take position "Left" side.

Thank you
