### ISSUE TITLE
[label] Please mention requirements in README of module

### ISSUE THREAD

**Issue by ecino** [JayVora-SerpentCS/SerpentCS_Contributions-v8#105]
The module label does not specify the requirements in the documentation, but it should do.

sudo pip install pyBarcode
sudo pip install utils
sudo pip install cairosvg

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/commit/1ebb180f1d877927f17a57d2e41028f1f07ae29c
