### ISSUE TITLE
[7.0] Invalid header declaration

### ISSUE THREAD

**Issue by zeroincombenze** [JayVora-SerpentCS/SerpentCS_Contributions-v8#113]
Odoo 7.0  import orm and fields from openerp not  model and api
Please loot at line 28 of:
/base_module_record/base_module_record.py

Thanks

**Comment by JayVora-SerpentCS** [comment]
In v7, there was no API

**Comment by zeroincombenze** [comment]
Yes there is no API
So why you wrote code with api and model?

Please look at line 28 of
/base_module_record/base_module_record.py

Thanks

**Comment by JayVora-SerpentCS** [comment]
strange, good catch that is!
Would you please register an issue if the error persists on install and run?
I doubt the backward compatability lets it run?

**Comment by zeroincombenze** [comment]
No thanks!
I understood you can understand the trouble and I prefer use software of other authors, more effordable.
Keep closed this issue and hide your mistakes under then the carpet.
Bye

**Comment by JayVora-SerpentCS** [comment]
Thank you for the response. It could be the result of the Pr made by contribs, its a pure mistake which will be corrected asap.
Appreciate your interest.
