### ISSUE TITLE
one2many_kanban_view o_tag not rendered when grouping records

### ISSUE THREAD

**Issue by pourjour** [JayVora-SerpentCS/SerpentCS_Contributions-v8#114]
I've noticed that when try to show tags in kanban view the module cannot let showing tags when grouping records

**Comment by JayVora-SerpentCS** [comment]
We are working out on this one.Thanks.

**Comment by pourjour** [comment]
Thank you for your hard work, I appreciate your help

**Comment by pourjour** [comment]
Thank you very much for your support :)
