### ISSUE TITLE
[Bug] Can't show images

### ISSUE THREAD

**Issue by ed29** [JayVora-SerpentCS/SerpentCS_Contributions-v8#119]
Hi:
There is a bug with odoo 10.0,it don't show images.

![default](https://user-images.githubusercontent.com/3096827/29125737-1fc78966-7d4f-11e7-9b81-38461b19385c.png)

**Comment by JayVora-SerpentCS** [comment]
We will check, Thanks.

**Comment by YogendrasinhChavda** [comment]
Hello @ed29 

I checked the product image in order lines, it works fine in odoo v10.
if the product has an image then it will show in Order lines when you select the product for order lines.

if you still getting the issue, Please elaborate more and make sure are you using modules is in odoo v10.

Thank you.
