### ISSUE TITLE
web_lead_funnel_chart - active vs archived leads and result listing

### ISSUE THREAD

**Issue by gezzzan** [JayVora-SerpentCS/SerpentCS_Contributions-v8#121]
Hello,

We tried out the Funnel Chart, it is very nice visually, but the data content (count of items) is confusing for us.

We use leads and archive them in this first stage if they seem to be spam or insufficient information, etc.

In the funnel chart these archived leads appear as "New", which is not correct in our use case, we would expect these to appear in the bottom as Archived.

Another thing, is that it would be great if clicking on a part of the chart or on the count of items the app would navigate to tree view listing the relevant items. This would make the app imho even more useful.  

thanks&cheers,
gezza

**Comment by JayVora-SerpentCS** [comment]
Checking soon.

**Comment by JayVora-SerpentCS** [comment]
#150 does it for you.
