### ISSUE TITLE
Should consider partner who are individuals. In that case, you should check for the parent_id.over_credit field.

### ISSUE THREAD

**Issue by v1n** [JayVora-SerpentCS/SerpentCS_Contributions-v8#133]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/blob/da0209603e7492f741c2aea95e359dc50e45a6db/partner_credit_limit/models/sale.py#L34

**Comment by JayVora-SerpentCS** [comment]
can you please make a PR?

**Comment by v1n** [comment]
Just created a PR. Thanks!
