### ISSUE TITLE
Image Preview Button problem

### ISSUE THREAD

**Issue by Dayssam** [JayVora-SerpentCS/SerpentCS_Contributions-v8#15]
Hi everyone,

Thanks for the nice module but i got this error when i click in image preview button

TypeError: this.$el.find(...).lightbox is not a function

http://localhost:9999/web_widget_multi_image/static/src/js/multi_image.js:248

**Comment by Dayssam** [comment]
in this line exactly

this.$el.find('.oe-image-preview').lightbox({

**Comment by JayVora-SerpentCS** [comment]
@Dayssam ,
Interesting, let me check.Shall keep you updated here.

**Comment by MeetSCS** [comment]
@Dayssam 

We have resolved the issue.

Can you please pull the latest branch ?

Thanks.

**Comment by Dayssam** [comment]
@MeetSCS 

Thx alot

it works like a charm

**Comment by JayVora-SerpentCS** [comment]
Thanks man!
Please share the ratings and testimonial on https://www.odoo.com/apps/modules/master/web_widget_multi_image/

**Comment by robpaz** [comment]
Doesn't work in Odoo 9. Please pretty please, fix it.....

Keep up the good work.

**Comment by SerpentCS** [comment]
Thanks @robpaz , we will do it asap.

**Comment by robpaz** [comment]
Thanks Mr Jay, dont forget the module name is

web_digital_sign

Best regards!

2015-12-01 1:25 GMT-04:00 SerpentCS notifications@github.com:
