### ISSUE TITLE
[odoo 10] Multi-DB Synchronization: how to configure manytomany relation

### ISSUE THREAD

**Issue by walterfrey** [JayVora-SerpentCS/SerpentCS_Contributions-v8#164]
Hello good Morning,

First, thank you for making the Multi-DB Synchronization open source module available. You're contributing so much to me that I'm starting.

How do I set up manytomany relation of odoo 10? I was able to synchronize some tables in isolation, but when I have relationships with another table I can not synchronize this relationship.

**Use Case:** I need to synchronize users and permissions between two databases. The user table has already managed to sync, but will not permissions, access settings.

Thank you in advance for your commitment.

Thank you.

**Comment by JayVora-SerpentCS** [comment]
@walterfrey Thanks for the appreciation.
In this case, make a config for the sync of permissions( record rules, ir model access and groups)
