### ISSUE TITLE
[ web_digital_sign ] read-only buffer after uninstalling

### ISSUE THREAD

**Issue by Ark74** [JayVora-SerpentCS/SerpentCS_Contributions-v8#165]
After uninstalling and removing the module **web_digital_sign** on version 10 CE,
Everytime I try to see enter a user profile from settings, I'm getting this error,

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 691, in dispatch
    return self._json_response(result)
  File "/opt/odoo/odoo-server/odoo/http.py", line 629, in _json_response
    body = json.dumps(response)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <read-only buffer for 0x7f33e73cdd70, size 11, offset 0 at 0x7f33e72646b0> is not JSON serializable

```

I've been able to reproduce this behavior twice, any advice on how to tackle this issue?
Thanks.

**Comment by JayVora-SerpentCS** [comment]
@Ark74 Strange enough, did not happen to me. Would you please tell me what other custom modules are in the instance?
-Another try : Make a simple db, install, uninstall the module.

**Comment by Ark74** [comment]
I must add that only modified profiles after deletion get this behavior, so if new users are created then they present this behavior. If i change the name of the user, also get this behavior.

Does it sounds as a db issue to you too?

**Comment by Ark74** [comment]
As for custom modules we have
* Remove odoo bindings
* United backend theme
* some themes
* and a pos password discount

Those may be them.

Update: By reinstalling the module I can access the users profile again. :laughing:

**Comment by Ark74** [comment]
After a 5 hour sit down reading databases tables, and logs turned out that the only necessary thing to complete the uninstall of the module without the reported error is to "Upgrade" the Web module.

Once the module is restored, then you seem to be back to normal. Cheers
