### ISSUE TITLE
web_digital_sign - when using this on DO, if there is a back order, signature is copied to it!

### ISSUE THREAD

**Issue by vcloud9ray** [JayVora-SerpentCS/SerpentCS_Contributions-v8#171]
We are using this module for deliveries made in a truck, and for customers to sign for their delivery.

If the driver cannot find something on the truck, and this item isn't delivered, a back order will be created.

Since the signature is taken before VALIDATE is clicked, the back order is created after the signature is captured.

Problem: the back order should NOT show the signature, as the customer HAS NOT signed for any of these items.

**Comment by vcloud9ray** [comment]
How can we reset the signature back to BLANK on the back order of the deliver?

**Comment by JayVora-SerpentCS** [comment]
We can set Copy=False on the specific field.

**Comment by JayVora-SerpentCS** [comment]
Let us know if this still does not work. We have a very good proposition for the delivery purpose - https://www.youtube.com/watch?v=roZbXESyhhg

**Comment by vcloud9ray** [comment]
Thanks for the rapid feedback.  Copy is not set to True.

![image](https://user-images.githubusercontent.com/31354495/35526561-ac983a6a-04dc-11e8-8134-50e7a35d6220.png)


Ray.

**Comment by JayVora-SerpentCS** [comment]
Forcefully, we have to set copy=False, otherwise copy sets to null.
Give it a try.

**Comment by hpatelserpentcs** [comment]
@vcloud9ray 

We are tested with adding new signature field in stock picking. set the copy=False on the field property.

![download](https://user-images.githubusercontent.com/26454900/35560327-20168a22-05d3-11e8-92e2-d08f0d8988de.png)

The back order not show the signature. Blank signature display in back order . 
![image](https://user-images.githubusercontent.com/26454900/35560459-7f880e9a-05d3-11e8-861d-65ae9f14b932.png)

![image](https://user-images.githubusercontent.com/26454900/35560548-bdd02f70-05d3-11e8-93a7-8f66fbebb250.png)

Thanks.
