### ISSUE TITLE
Error While Using the Widget on V11

### ISSUE THREAD

**Issue by ghulammasood** [JayVora-SerpentCS/SerpentCS_Contributions-v8#182]
While trying to use the widget with any binary field an error is popping up, leading to JS files. Don't exactly have the idea of what the actual problem is.

**Comment by JayVora-SerpentCS** [comment]
@ghulammasood Can you please share the screenshot?

**Comment by citruscorp** [comment]
It will be that the web_tree_image module is not migrated in v11?

**Comment by JayVora-SerpentCS** [comment]
Its not yet migrated IMHO

**Comment by JayVora-SerpentCS** [comment]
It seems working fine on v11. Make sure, you have set multi image true in website -> configuration -> Setting.
![multiimagesetting](https://user-images.githubusercontent.com/5909386/37703354-6d250afe-2d1b-11e8-915c-da8fe793e815.png)
![screenshot2](https://user-images.githubusercontent.com/5909386/37703355-6d466ee2-2d1b-11e8-9304-e7084df27702.png)
![screenshot](https://user-images.githubusercontent.com/5909386/37703356-6d645ff6-2d1b-11e8-8f71-f6b8bfe065ba.png)
