### ISSUE TITLE
Web digi sign - Does not work except on Firefox

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#185]
Khalid Fardan <5alid@5alid.org> Reported that the widget in v11 does not work on other browsers except Firefox.

![fnekhcblgpfbcheb](https://user-images.githubusercontent.com/5909386/37703501-debbc61c-2d1b-11e8-95c2-1509e2a07c02.png)

Also, test on iPAD and Android Tablets/Mobile.

Thanks,

**Comment by dhirendrasinh-Serpent** [comment]
@Khalid Fardan
Take latest source code/pull of version 11 odoo addons and then try to use this.
It might solve the issues. just to check it.

If the issue is not solve please send your Skype id on this "d.thakor.serpentcs@gmail.com" email ID.
