### ISSUE TITLE
Error While Testing Web Digital Sign

### ISSUE THREAD

**Issue by ghulammasood** [JayVora-SerpentCS/SerpentCS_Contributions-v8#186]
@SerpentCS 

Sorry for getting back late. 

The error however still persists, i have enabled the settings option u mentioned on via the snapshots, I am attaching the snapshots of error i am getting while trying to save the signature for any user. 

![screenshot from 2018-03-21 15-41-51](https://user-images.githubusercontent.com/12405783/37705777-efd79766-2d1e-11e8-86ca-c7db38f960e9.png)
![screenshot from 2018-03-21 15-41-58](https://user-images.githubusercontent.com/12405783/37705778-f008da60-2d1e-11e8-9db8-0c4a92a78ca2.png)
![screenshot from 2018-03-21 15-42-04](https://user-images.githubusercontent.com/12405783/37705779-f03b6b38-2d1e-11e8-9778-10b47932e8f7.png)
![screenshot from 2018-03-21 15-42-10](https://user-images.githubusercontent.com/12405783/37705780-f06c29b2-2d1e-11e8-8cc2-3da82fdcff5c.png)
![screenshot from 2018-03-21 15-42-52](https://user-images.githubusercontent.com/12405783/37705781-f0c71cd2-2d1e-11e8-9dbd-b42a6c5ad847.png)

Let me know if anything else is required from my testing,

**Comment by Hetal-SerpentCS** [comment]
@ ghulammasood 
I am afraid I do not face the issue  that you are referring to, please if possible could you provide me access to your demo instance to understand your issues and help me fix it.

I am using chrome Version 55.0.2883.87 (64-bit) which chrome version are you using ??

**Comment by ghulammasood** [comment]
@Hetal-SerpentCS I tried it both on Chrome and firefox. 

Chrome : 65.0.3325.181 (Official Build) (64-bit)
Firefox : 59.0.1 (64-bit)

**Comment by ghulammasood** [comment]
@Hetal-SerpentCS I can give u access to my machine let me know ur skype so that we can have a session to look into the issue, thanks for cooperation.

**Comment by Hetal-SerpentCS** [comment]
@ghulammasood 
Let me check with browser version which you mention here and i will update you soon.

**Comment by ghulammasood** [comment]
@Hetal-SerpentCS Thanks. 

Is there a possibility that i am missing something while tesing? If that is the case also let me know

**Comment by Hetal-SerpentCS** [comment]
@ghulammasood 
No, you don't need to configure anything else just install module and you are able to Draw a Digital Signature.
I have tested with latest browser version chrome : Version 65.0.3325.181 (Official Build) (64-bit) and Firefox : 60.0b5 (64-bit). But still I am not facing any issue.

**Comment by Hetal-SerpentCS** [comment]
@ghulammasood 
If you have any query regarding this issue please contact to "d.thakor.serpentcs@gmail.com" email.
And send your Skype id on this Email Id.

**Comment by ghulammasood** [comment]
@Hetal-SerpentCS For sure, I will share the details on the mail u mentioned. 

Thanks for ur help.

**Comment by ghulammasood** [comment]
Hi @Hetal-SerpentCS 
Have sent the email on the mail u mentioned. 
Thanks

**Comment by ghulammasood** [comment]
Hi @Hetal-SerpentCS,
The issue was explained to "d.thakor.serpentcs@gmail.com" we debugged the error together at my environment and the guy took notes of it, pl update when the fix has been made for it.

**Comment by ghulammasood** [comment]
@Hetal-SerpentCS thanks for your cooperation the issue is resolved.

**Comment by ThakorDhirendrasinh** [comment]
@ghulammasood
Take latest source code/pull of version 11 odoo addons,it will surely solve your problem.
