### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by loikki** [JayVora-SerpentCS/SerpentCS_Contributions-v8#19]
Hi,
I have seen in the version 7 that you have a label printing model (https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v7/tree/master/label). Did I miss it? If not, are you planning to upgrade it soon or should I do it? Thank you in advance

**Comment by JayVora-SerpentCS** [comment]
We are working on it,shall publish.
If you are looking for dedicated development, so let us know on jay.vora@serpentcs.com
Thanks.

**Comment by loikki** [comment]
I have already started to convert the code. If you want, I will do a pull request as soon as I am ready to do it

**Comment by JayVora-SerpentCS** [comment]
That would be great!

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8 has it now!
