### ISSUE TITLE
[10.0] web_digital_sign - Incorrect behaviour when field is READONLY with SIGNATURE widget

### ISSUE THREAD

**Issue by vcloud9ray** [JayVora-SerpentCS/SerpentCS_Contributions-v8#192]
I created a field that uses the Widget and set attrs to make it readonly when the stock.picking is DONE:

![image](https://user-images.githubusercontent.com/31354495/38471421-d1c61fb2-3b25-11e8-9aad-ea38dbdb1b8f.png)

The two fields above also have the same attrs, note how they are READONLY in EDIT mode:

![image](https://user-images.githubusercontent.com/31354495/38471433-f3f2af10-3b25-11e8-9cfa-e0b3d634c0d2.png)

Two things happen when the EDIT button is clicked on the record.

1) The CLEAR button can be clicked, erasing the signature.
2) The signature will clear as soon as someone clicks EDIT then SAVE (with no other changes).

How can the data in this field be made READONLY without allowing users to click the CLEAR button?

How can the data in this field be made READONLY without the contents clearing when EDIT is clicked on the record, as making it READONLY will clear the contents.

**Comment by JayVora-SerpentCS** [comment]
Thanks for reporting Ray. We will check this asap.

**Comment by JayVora-SerpentCS** [comment]
@vcloud9ray check plz
