### ISSUE TITLE
Problem when updating module list

### ISSUE THREAD

**Issue by akram1** [JayVora-SerpentCS/SerpentCS_Contributions-v8#2]
My odoo is v8 build 30/1/2015 Linux64bit
after installing product_brand, I copied website_product_brand to addons and update the module list as usual but odoo raised an error
"/media/akram/Data/projects/servers/Odoo8/source/addons/website_product_brand/controllers/__init__.py", line 22, in <module>
    import main
  File "/media/akram/Data/projects/servers/Odoo8/source/addons/website_product_brand/controllers/main.py", line 9, in <module>
    from gi.overrides.keysyms import currency
ImportError: No module named gi.overrides.keysyms

I fixed this by removing line 9 in website_product_brand/controllers/main.py:
from gi.overrides.keysyms import currency

**Comment by JayVora-SerpentCS** [comment]
Dear Akram,

You should try this:
sudo apt-get install python-gobject

Thanks.
