### ISSUE TITLE
Signature widet shows error in one2many field.

### ISSUE THREAD

**Issue by ghost** [JayVora-SerpentCS/SerpentCS_Contributions-v8#206]
The above module working fine in normal form. But we are facing issue while adding signature fields in one2many related table. For example, Sale order Line added signature fields and created new entry added signature, while edit and save record facing below.
 error:- TypeError: this.find(...).add(...).data(...) is undefined Please let me know the possible solutions to fix the above issue.

**Comment by JayVora-SerpentCS** [comment]
@NishaGajjar-SerpentCS Check with #Nikita

**Comment by ghost** [comment]
Hello, 
Issue is not fix yet. it's show again error. See attached file.
It's happen when i am signature inside one2many field and save one2many(child) after when i am re-open same record as well as re-signature same record without save your form view(parent).
![one2many](https://user-images.githubusercontent.com/30867122/41334296-b931828c-6f02-11e8-902b-f7b666fcec62.png)

**Comment by NishaGajjar-SerpentCS** [comment]
Hello Sir,

Already checked it by installing in local for version 10 and 11, we are not
facing any issue,
Its working properly.
This error might generated due to some another installed custom module.
---
Regards,
*Nisha Gajjar*
Software Developer,
Serpent Consulting Services Pvt. Ltd.! <http://www.serpentcs.com>

**Comment by JayVora-SerpentCS** [comment]
@NishaGajjar-SerpentCS Try adding the signature widget in o2m field.

**Comment by NishaGajjar-SerpentCS** [comment]
Sir,
We have followed same steps mentioned in comments by adding one binary
field in sale order line
with widget signature,and its working.
---
Regards,
*Nisha Gajjar*
Software Developer,
Serpent Consulting Services Pvt. Ltd.! <http://www.serpentcs.com>

**Comment by ghost** [comment]
Hello @NishaGajjar-SerpentCS 
I am just add one one2many field in form view and inside one2many field add one binary field. it's just show error which one image  show in previous message. and i am follow the following steps :
1. first sign in one2many field and don't save parent from.
2. Re-open your one2many(Child) record. at this time you are facing problem.

**Comment by NishaGajjar-SerpentCS** [comment]
Hello @manishkumarbohra,
Thanks for the steps.

**Comment by JayVora-SerpentCS** [comment]
#239 Closed this, thanks.
