### ISSUE TITLE
[9.0]web_digital_sign: Signature is not saved when attrs(Readonly) is applied and widget is used multiple time in same view.

### ISSUE THREAD

**Issue by Swapnesh-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#248]
**Impacted versions:** V9 Ent

**Steps to reproduce:**
Add two or more binary fields and use `widget="signature"` apply `readonly` attribute based on some domain.

![s1](https://user-images.githubusercontent.com/36026345/42432936-ac07f7ae-836a-11e8-8b59-a34754813e1f.png)

Record Signature and Save the Records.
**Current behavior:**
Signature is not visible.
![s2](https://user-images.githubusercontent.com/36026345/42432939-b222b660-836a-11e8-94da-e9f31a0daeb6.png)

**Expected behavior:**

Signature Should be there.

**Comment by hpatelserpentcs** [comment]
@Swapnesh-SerpentCS 

Solved.
