### ISSUE TITLE
Library issue in Label Module

### ISSUE THREAD

**Issue by SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#25]
No module name utils and cairosvg.

**Comment by SerpentCS** [comment]
We have checked label module issue.

For 'No module name barcode' you need to install package pyBarcode-0.7. You can find or download the python package here https://pypi.python.org/pypi/pyBarcode/0.7

For 'No module name utils' you need to install package utils-0.8.0. You can find or download the python package here https://pypi.python.org/pypi/utils

After installing this package, another library cairosvg also you need to install in your system. To install this library you need to fire this command : sudo apt-get install python-cairosvg or sudo pip install cairosvg.

Hope this will help.

Thanks,

**Comment by bleuubuntu** [comment]
Good I manage to install all the 3 but now i have this (I am on odoo 9)
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (403, 1, 2015-12-16 20:01:48.389075, null, 1, 2015-12-16 20:01:48.389075, null, ir.actions.report.xml, null, null, t, pdf, null, null, null, null, null, t, null, f, null, null, null, f, null, 5, null, f, f).
" while parsing /opt/odoo/custom/addons/label/label_report.xml:5, near
<record id="dynamic_label" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="label.paperformat_euro"/>
        </record>

**Comment by SerpentCS** [comment]
@bleuubuntu Make sure you are using latest branch. 
Kindly pull the branch and try to install the module again.

Hope this will help.
Thanks,

**Comment by SerpentCS** [comment]
Run:
sudo pip install pyBarcode
sudo pip install utils
sudo pip install cairosvg
