### ISSUE TITLE
[11.0][project_kanban] Non loaded modules:       ["project_team.form_rel"]

### ISSUE THREAD

**Issue by SalahAdDin** [JayVora-SerpentCS/SerpentCS_Contributions-v8#252]
Hi, I'm using your module for my instance, and I'm getting this warning in the browser console, what does it mean?

_**Update:**_
I reviewed this developer documentation's based and i found a related problem:
`Missing dependencies: (2) ["web.form_relational", "web.form_common"]`
![issue](https://user-images.githubusercontent.com/5034215/42639741-705fea40-85f9-11e8-9e1a-4ad466aae564.png)

**_Update:_**
I could see that those modules are present in `odoo` 10.0 and I think they are not in 11.0.
Yes, it is: https://github.com/odoo/odoo/tree/10.0/addons/web/static/src/js/views

**_Update:_**
This is the console message that i get with `Developer mode with assets`:
```bash
Debug:                    
{project_team.form_rel: {…}}
project_team.form_rel
:
dependencies
:
(3) ["web.form_relational", "web.core", "web.form_common"]
dependents
:
[]
missing
:
(2) ["web.form_relational", "web.form_common"]
name
:
"project_team.form_rel"
```

I think it requires an update.

Thank you very much.

**Comment by JayVora-SerpentCS** [comment]
We will definitely check, thanks.

**Comment by SalahAdDin** [comment]
Your welcome

**Comment by SalahAdDin** [comment]
Related: https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/issues/254

**Comment by SalahAdDin** [comment]
Also i have two warnings:
`Missing widget:  many2many_kanban  for field team_members of type many2many` and `Missing widget:  checkbox  for field group_website_multiimage of type boolean`

**Comment by SalahAdDin** [comment]
@JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
We would appreciate your contribution too. Feel free to add your own bit. We will check and do the needful.

**Comment by SalahAdDin** [comment]
Unfortunately, i don't know how can i contribute to solve this issue.

**Comment by SalahAdDin** [comment]
Thank you very much. It works like a charm.
