### ISSUE TITLE
label module install issue

### ISSUE THREAD

**Issue by SaFi2266** [JayVora-SerpentCS/SerpentCS_Contributions-v8#26]
Hello,
while trying install label module I get the error

```
ParseError: "null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (434, 1, 2015-12-03 13:06:59.014656, null, 1, 2015-12-03 13:06:59.014656, null, ir.actions.report.xml, null, null, t, pdf, null, null, null, null, t, null, f, null, null, null, f, null, 5, null, f, f).
" while parsing /opt/custom/addons/label/label_report.xml:5, near
<record id="dynamic_label" model="ir.actions.report.xml">
            <field name="paperformat_id" ref="label.paperformat_euro"/>
        </record>
```

any help will be welcomed

**Comment by ghost** [comment]
Hello Safi,

Issue is resolved in latest code.

Can you please check ?

Thanks.

**Comment by SaFi2266** [comment]
Yes, the issue was solved and now **label** module installed correctly.
thank you very much for your efforts and for your quick response.
Regards,
SaFi

**Comment by SaFi2266** [comment]
Marked [Solved]

**Comment by SerpentCS** [comment]
@MeetSCS would be great to mention the commit reference.

**Comment by SaFi2266** [comment]
Hello Again,

I confirmed that the issue #26
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/issues/26
was solved and closed successfully, but I submitted new one #27
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/issues/27
So please check and review it

TIA
Regards,
SaFi

**Comment by ghost** [comment]
Hello Safi,

We are checking the issue.

Can you please provide the steps to reproduce issue ?

Thanks.

**Comment by SaFi2266** [comment]
OK
1- Go to settings -> label print -> create new
2- Name -> tcard and Model->Product
3- Add fields Name and Sale Price with normal type and distinct sequences
4- Save
5- Go to advance & generate sidebar button & save again
6- Go to Sales -> Product Variants -> well configured product with internal code & EAN13 code
7- From more menu select Label(tcard)
8- get the error

```
File "/opt/custom/addons/label/report/dynamic_label.py", line 118, in get_data
    remain_data.append( newlist_data)
QWebException: "local variable 'newlist_data' referenced before assignment" while evaluating
"get_data(data['form'].get('rows'),data['form'].get('columns'),data['form'].get('ids'),data ['form'].get('model'),data['form'].get('number_of_copy'))"
```
