### ISSUE TITLE
[11.0][project_kanban][info]Project teams are not directly related with projects

### ISSUE THREAD

**Issue by SalahAdDin** [JayVora-SerpentCS/SerpentCS_Contributions-v8#260]
As you can see in the next gif if you don't assing a project team by default, in the `team` tab you can add users but they won't be a team:
![deepin-screen-recorder_select area_20180803203058](https://user-images.githubusercontent.com/5034215/43656935-e8f512ae-975c-11e8-81bf-a61746eb9cc7.gif)

I want to know if it is the waited behaviour, because, at least for me, the initial perception is to create a new team for that project since its `team` tab.

Thank you.

**Comment by JayVora-SerpentCS** [comment]
You are allowed to add as many members outside team too. The actual purpose is to allow members in single choice of team. Editing /Adding /Removing members runtime is fine.
