### ISSUE TITLE
label module printing error

### ISSUE THREAD

**Issue by SaFi2266** [JayVora-SerpentCS/SerpentCS_Contributions-v8#27]
Hello Braves
 When trying print product labels I get this error

```
File "/opt/custom/addons/label/report/dynamic_label.py", line 118, in get_data
    remain_data.append( newlist_data)
QWebException: "local variable 'newlist_data' referenced before assignment" while evaluating
"get_data(data['form'].get('rows'),data['form'].get('columns'),data['form'].get('ids'),data ['form'].get('model'),data['form'].get('number_of_copy'))"
```

will you please check and try to fix it
Thanx
SaFi

**Comment by SaFi2266** [comment]
OK
1- Go to settings -> label print -> create new
2- Name -> tcard and Model->Product
3- Add fields Name and Sale Price with normal type and distinct sequences
4- Save
5- Go to advance & generate sidebar button & save again
6- Go to Sales -> Product Variants -> well configured product with internal code & EAN13 code
7- From more menu select Label(tcard)
8- get the error

```
File "/opt/custom/addons/label/report/dynamic_label.py", line 118, in get_data
    remain_data.append( newlist_data)
QWebException: "local variable 'newlist_data' referenced before assignment" while evaluating
"get_data(data['form'].get('rows'),data['form'].get('columns'),data['form'].get('ids'),data ['form'].get('model'),data['form'].get('number_of_copy'))"
```

**Comment by ghost** [comment]
Hello Safi,

We have resolved the issue in latest code,

commit refrence --> https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/commit/97522d7d82696662b302a0935998ba6ce2857d72 

Can you please check ?

Waiting for your feedback.

Thanks.

**Comment by SaFi2266** [comment]
Hello,
Sorry for delay
Yes, it's working OK.
Thank you
