### ISSUE TITLE
web_digital_sign - New Feature Request

### ISSUE THREAD

**Issue by Boss1669** [JayVora-SerpentCS/SerpentCS_Contributions-v8#273]
web_digital_sign - New Feature Request
1.need to have take photo icon option left to “clear” or “save” like this
![pasted image 0](https://user-images.githubusercontent.com/26357404/44763682-82939200-ab76-11e8-9614-e6784208b5a5.png)

So when press on “Camera Logo” on mobile it will open gallery or take a photo (preferably take a photo but if can't it will need open gallery of the device)

Pressing Clear will be clear that image

Why i want to do this is that sometime we get a customer sign on paper, and we need that signature to put it digitally in our system

**Comment by JayVora-SerpentCS** [comment]
We consider add in next release, thanks.
