### ISSUE TITLE
[10.0] web_one2many_kanban - search filters break in kanban views

### ISSUE THREAD

**Issue by timotalvitie** [JayVora-SerpentCS/SerpentCS_Contributions-v8#276]
We stumbled upon a problem in the web_one2many_kanban module that causes kanban views' search filter to break in some Odoo core kanban views. The following hopefully describes the issue:

Steps to reproduce:
-Install fresh Odoo 10.0 with demo data
-Install the hr_recruitment module
-Install the web_one2many_kanban module
-Go to Recruitment -> Job Positions
-Click the "Application(s)" button in the "Marketing and community manager" job position box

Current behavior:
-Applications for all job positions are shown in the kanban view. Filtering is applied only after you hit enter in the search box and reload the kanban contents.

Expected behavior:
-Applications for just the "Marketing and community manager" job position are shown immediately, without having to reload the kanban contents.

Uninstalling the web_one2many_kanban removes the problem.

**Comment by timotalvitie** [comment]
Here's also a screenshot of the issue
![serpent_issue](https://user-images.githubusercontent.com/7382150/45861812-7666b300-bd77-11e8-96cb-f46f61ba1598.jpeg)

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs
