### ISSUE TITLE
Try to Scheduled Actions on base_synchro 

### ISSUE THREAD

**Issue by ahmedqudah** [JayVora-SerpentCS/SerpentCS_Contributions-v8#28]
hi guys ,,
it's great job you are done for these module , but i'm try to add scheduled action to automate this module and have this error :

2015-12-06 10:14:50,111 56809 ERROR test_auto openerp.addons.base.ir.ir_cron: Call of self.pool.get('base.synchro').upload_download_multi_thread(cr, uid, _()) failed in Job 9
Traceback (most recent call last):
  File "/home/ahmed/workspace/odoo8/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/home/ahmed/workspace/odoo8/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, *_kwargs)
TypeError: old_api() takes at least 4 arguments (3 given)

im use odoo 8 ,
can you help me please,,,
thanks a lot

**Comment by JayVora-SerpentCS** [comment]
@ahmedqudah please tell us the cron method you wrote on config!

**Comment by ahmedqudah** [comment]
@JayVora-SerpentCS 
this is the method ,,,,
![screenshot from 2015-12-07 08 50 55](https://cloud.githubusercontent.com/assets/10090177/11620971/3c573d90-9cc0-11e5-8335-ad911e0e5137.png)
![screenshot from 2015-12-07 08 50 15](https://cloud.githubusercontent.com/assets/10090177/11620970/3c53fb12-9cc0-11e5-8bd1-03b2a8728cd7.png)

**Comment by SerpentCS** [comment]
@ahmedqudah the method you are calling from the scheduler, is the method of the wizard.
You cannot call such method from the scheduler as the method accepts parameter like ids.

**Comment by JayVora-SerpentCS** [comment]
Closing the issue for now, as we have migrated to v9 n v10. Let us know if this happens again.
