### ISSUE TITLE
[10.0] web_groupby_expand - click on next raise a JS error

### ISSUE THREAD

**Issue by BT-aestebanez** [JayVora-SerpentCS/SerpentCS_Contributions-v8#280]
Hi,

The steps to reproduce this issue are:
- Go to a list view with enough records to split them in several pages
- Group them: ensure at least one of the resulting groups have enough records to split them in several pages
- Try to click on the next button to go to the next page of records

Solution:
- Adding return on the render method as odoo does by default:
https://github.com/odoo/odoo/blob/93d69933acc9454a5741fe6eb39edd9cdae9fbf1/addons/web/static/src/js/views/list_view.js#L1573

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs
