### ISSUE TITLE
[11.0] web_groupby_expand

### ISSUE THREAD

**Issue by 1500cc** [JayVora-SerpentCS/SerpentCS_Contributions-v8#289]
The add-on doesn't seem to run as the button does not appear in the search view.

Please add support for Odoo V11 too

**Comment by JayVora-SerpentCS** [comment]
Which addon you talk about ? Explain please.

**Comment by 1500cc** [comment]
Sorry for missing out the name, it is: web_groupby_expand

I have installed it but it the expand button is not being shown as in the screenshots in the odoo download page.
