### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by moturi12** [JayVora-SerpentCS/SerpentCS_Contributions-v8#3]
Can you provide small snippet of using this module

Thanks,
Naran

**Comment by JayVora-SerpentCS** [comment]
Hello,
Add widget='signature' as stated in the video. The User model has it.
Thanks.

**Comment by lukebranch** [comment]
@JayVora-SerpentCS ,

Thanks for the awesome work, i've been looking for a way to add this to quotations among many other things. Do you have a link to the video?

I'd like to make an instructional forum post in help.odoo.com explaining how to use it, as I'm sure there are lots of people out there that would benefit from this module.

**Comment by JayVora-SerpentCS** [comment]
@lukebranch , Please get the latest code!
