### ISSUE TITLE
Odoo 12: 'report.label.report_label' AttributeError

### ISSUE THREAD

**Issue by cristian-g** [JayVora-SerpentCS/SerpentCS_Contributions-v8#304]
I am using your module in Odoo to do mass label printing ([https://www.odoo.com/apps/modules/12.0/label/][1]) and despite the fact that the module seems to be compatible with version 12 as stated in the specification page, I am getting server errors when trying to run the pdf rendering:

    Odoo Server Error

    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1677, in report_download
    response = self.report_routes(reportname, converter=converter, **dict(data))
     File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
    File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1614, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
    File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 677, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
    File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 710, in render_qweb_html
    data = self._get_rendering_context(docids, data)
    File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 723, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
    AttributeError: 'report.label.report_label' object has no attribute '_get_report_values'

Screenshot:
[![enter image description here][2]][2]

It may be an error related to the change of some Odoo version (or not, I don’t really know).

Does anyone know if this attribute exist? I haven’t been able to find this information in the Odoo documentation (it doesn’t seem very complete regarding these topic).

Here are some screenshots of the configurations I’m using:

[![Odoo][3]][3]
[![Odoo][4]][4]
[![Odoo][5]][5]
[![Odoo][6]][6]

Thank you for your help!

  [1]: https://www.odoo.com/apps/modules/12.0/label/
  [2]: https://i.stack.imgur.com/wmt92.png
  [3]: https://i.stack.imgur.com/UPOOk.png
  [4]: https://i.stack.imgur.com/Zlvns.png
  [5]: https://i.stack.imgur.com/yIbg5.png
  [6]: https://i.stack.imgur.com/bqWRV.png

**Comment by cristian-g** [comment]
From the traceback on first screenshot, the problem seems to be with `report_model` variable which is reference to `report.label.report_label` object, defined in `label/report/dunamic_model.py` file which contains the method `get_report_values`. But from odoo 12 community code, `ir.actions.report` is looking for `_get_report_values`, the mismatch between this two method name seems to be actually causing the problem. Any ideas? @JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS take a look.

**Comment by Chandresh-SerpentCS** [comment]
@JayVora-SerpentCS Ok, I will check.

**Comment by cristian-g** [comment]
Temporal workaround:

> In module go to report > dynamic_label.py file and change method name from get_report_values to _get_report_values.

The pdf generation is now working. By the way, now the generated pdf is blank (empty page), with 0 bytes. Am I missing something? It could be that my configuration is wrong. Do you have any working example? Thank you so much.

**Comment by JayVora-SerpentCS** [comment]
Ping @Chandresh-SerpentCS

**Comment by Chandresh-SerpentCS** [comment]
> From the traceback on first screenshot, the problem seems to be with `report_model` variable which is reference to `report.label.report_label` object, defined in `label/report/dunamic_model.py` file which contains the method `get_report_values`. But from odoo 12 community code, `ir.actions.report` is looking for `_get_report_values`, the mismatch between this two method name seems to be actually causing the problem. Any ideas? @JayVora-SerpentCS

@cristian-g @JayVora-SerpentCS This issue is confirmed. We will update the code on GitHub. Yes we need to change the method name as `_get_report_values`.

**Comment by Chandresh-SerpentCS** [comment]
> Temporal workaround:
> 
> > In module go to report > dynamic_label.py file and change method name from get_report_values to _get_report_values.
> 
> The pdf generation is now working. By the way, now the generated pdf is blank (empty page), with 0 bytes. Am I missing something? It could be that my configuration is wrong. Do you have any working example? Thank you so much.

I checked, but I did not find any issue in report printing. Report printed successfully with label content.

![screenshot from 2019-02-08 16-52-28](https://user-images.githubusercontent.com/17649094/52475799-b6152680-2bc2-11e9-89bb-87503b447641.png)

**Comment by Chandresh-SerpentCS** [comment]
PR #311
