### ISSUE TITLE
[11.0] Web Widget Multi Image Buttons

### ISSUE THREAD

**Issue by rowemoore** [JayVora-SerpentCS/SerpentCS_Contributions-v8#305]
The "Image Preview" and "List All Images" buttons are showing up on all X2ManyControlPanels.  Is there a way to limit the buttons to only the models and the notebook pages in those modules (i.e. Images) using the module?  
![screenshot 89](https://user-images.githubusercontent.com/14188201/51053736-590c5d80-158f-11e9-9f44-bfb05223e242.png)
![screenshot 91](https://user-images.githubusercontent.com/14188201/51053742-60336b80-158f-11e9-9740-803a49e65fde.png)

**Comment by JayVora-SerpentCS** [comment]
@Dhirendrasinh-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
Fixed in latest push
