### ISSUE TITLE
[8.0] The resolutions of images depends on the first image

### ISSUE THREAD

**Issue by TimLai125** [JayVora-SerpentCS/SerpentCS_Contributions-v8#306]
I have installed the `website_multi_image_zoom` on my v8.0 environment.
Now multi-images can be shown in the website, however the images other than the first images are squeezed to the resolution of the first image.

The first image:
![image](https://user-images.githubusercontent.com/27185427/51104127-2af17c80-1820-11e9-9064-1031b0c856f8.png)

The Second image:
![image](https://user-images.githubusercontent.com/27185427/51104154-3e9ce300-1820-11e9-9fcc-60b2562186b1.png)

**Comment by TimLai125** [comment]
Hi @JayVora-SerpentCS
Can you comment on this?

**Comment by JayVora-SerpentCS** [comment]
@Dhirendrasinh-SerpentCS pls chk

**Comment by dhirendrasinh-Serpent** [comment]
Done #308
