### ISSUE TITLE
Asking about the synchro

### ISSUE THREAD

**Issue by johnbangad** [JayVora-SerpentCS/SerpentCS_Contributions-v8#310]
Hello, I am able to sync basic data such as sales order and purchase order with invoice in draft stage and delivery in ready stage. For invoice once I validate the invoice and sync the target will receive it and put the invoice to paid already. is the module able to sync deliveries,transfers, stock move or accounting entries like journal items. registering payments for vendors and customers?? 

Thanks in advance.

**Comment by JayVora-SerpentCS** [comment]
@johnbangad the module can sync any tables here

**Comment by johnbangad** [comment]
May I ask if someone from you team may help me on synchronizing?

**Comment by JayVora-SerpentCS** [comment]
Sure @johnbangad We offer professional support. Contact on https://www.serpentcs.com/contact-us
