### ISSUE TITLE
cant import Vendors

### ISSUE THREAD

**Issue by jayo2004** [JayVora-SerpentCS/SerpentCS_Contributions-v8#317]
Odoo 10

I am trying to import a list of products using import_export_templating. Everything imports except Vendors. This is a one2many relationship. Are there any issues doing this. No errors just doesnt imports. I also created the Vendor before import

**Comment by JayVora-SerpentCS** [comment]
@jayo2004 It seems work pretty smooth. Would you please send an example what sheet are you importing?
Thanks.

**Comment by jayo2004** [comment]
Hi @JayVora-SerpentCS  You can download sample file here

[https://mega.nz/#!UcxnTQDI!G_6lUvGNE7XKKOPWUohSPxwuDj9qIrx-NHQPQfkhY48](url)

**Comment by jayo2004** [comment]
Hello the file is attached that I am trying to import. As I said everything
imports except Vendors. I created the Vendor also Before import.

**Comment by jayo2004** [comment]
@JayVora-SerpentCS  Any update on this? Can you confirm if there is an issue?

**Comment by JayVora-SerpentCS** [comment]
Assigned to a teammate.

**Comment by murtuzasaleh** [comment]
@jayo2004 
Follow the below steps:-
1) Go to Export and Download the Blank templates of **Information about a product vendor**. (All the required fields and Product Template field).

2) Add your data in **Information about a product vendor** template and import it.

So it will import vendors details in the product.

For the one2many relationship, we have already mentioned it in our template format.

![temp](https://user-images.githubusercontent.com/20418904/53548170-e3684b00-3b56-11e9-8b4b-2d86c965f206.png)
