### ISSUE TITLE
[v11.0] web_digital_sign required parameter don't work

### ISSUE THREAD

**Issue by ajaychauhan727** [JayVora-SerpentCS/SerpentCS_Contributions-v8#318]
**Steps to Reproduce:**
Add required="1" along with widget="signature"

**Current Behaviour**
Even if it shows required in debug mode it allows us to save without adding any **sign**

**Expected Behaviour**
There should be prompt for required field

**Check Video**
![signature_required_issue](https://user-images.githubusercontent.com/5329501/53242095-cb617900-36c9-11e9-974e-398b4d90d9d5.gif)

**Comment by Swapnesh-SerpentCS** [comment]
Hello @ajaychauhan727, 

Thanks for Reporting this to us,

This is known the limitation because of the `widget="signature"` which contains default data inside. (You can check in Database.)

Ps: You can compare and check inside create/write. 
Cc: @JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
@Swapnesh-SerpentCS think for a proposable solution.

**Comment by Swapnesh-SerpentCS** [comment]
> @Swapnesh-SerpentCS think for a proposable solution.

Sure, I will have a look.

**Comment by Swapnesh-SerpentCS** [comment]
@ajaychauhan727 
You can compare `vals` in for  signature field in `create`/`write` method add Validation.

(As `widget="signature"` adds default data form Preview, Similar to HTML field)

**Comment by JayVora-SerpentCS** [comment]
is this supposed to closed now?
Thanks.

**Comment by ajaychauhan727** [comment]
Hi @Swapnesh-SerpentCS ,

I have checked the vals in create, yes I am getting some value for Signature. If I remove widget='signature' it works well.

Btw, What should I compare to validate it's default value ?

Can't we have validation from widget side, because otherwise in all object we need to call that validate method.

Regards,

**Comment by drashtipatel24** [comment]
Hello @ajaychauhan727,

I have tested this module, widget="signature" is perfectly working with the required=1.

Please check this image.

![Screenshot from 2019-12-17 11-31-48](https://user-images.githubusercontent.com/25099461/70969195-554b5a00-20c1-11ea-9c56-1d173434416f.png)
