### ISSUE TITLE
Conflict with sale_layout

### ISSUE THREAD

**Issue by MiguelMachadoM** [JayVora-SerpentCS/SerpentCS_Contributions-v8#32]
@JayVora-SerpentCS 

note to the readme

Can't install it if have installed sale_layout.

**Comment by JayVora-SerpentCS** [comment]
Which module please?

**Comment by MiguelMachadoM** [comment]
@JayVora-SerpentCS
https://github.com/OCA/OCB/tree/8.0/addons/sale_layout

**Comment by JayVora-SerpentCS** [comment]
@Razztak  which module does it get a conflict with sale_layout? Please be specific.

**Comment by IbrahimMAbed** [comment]
sales_report_product_image

**Comment by JayVora-SerpentCS** [comment]
Guess I understand, the purpose is different hence there is no dependency. should you want us to develop, let us know.
