### ISSUE TITLE
[12] Hide Price and Discount : Price displayed on sections & Website

### ISSUE THREAD

**Issue by gregory-moka** [JayVora-SerpentCS/SerpentCS_Contributions-v8#323]
Hello,

Even if the prices are hidden on products details, if you add sections on your sale order, the amount is displayed on it.
It's is the same for the portal version, template aren't affected by the app. You should hide price and discount too on this page.

**Comment by JayVora-SerpentCS** [comment]
@gregory-moka Thank you for the suggestion. @AnilKesariya please check.

**Comment by AnilKesariya** [comment]
@JayVora-SerpentCS, Sure. I will check. thanks.

**Comment by AnilKesariya** [comment]
@gregory-moka, do you mean that we should display the price and disount on sale order view when those are enabled from product view? right now it is enabled on report of sale order when you set flag to true on order. can you write an example what behavior do you expect?

Regards,
Anil RK

**Comment by JayVora-SerpentCS** [comment]
@gregory-moka Can you revert please?

**Comment by gregory-moka** [comment]
Hello,
sorry, yes, my team worked on a commit, we will bring you the fork as soon as possible.
Up to you to implement the correction in your code.

**Comment by gregory-moka** [comment]
Here is the link to the gitlab project with all the modifications done : 
https://gitlab.com/CorentinFs/sale_report_hide_price_topush

**Comment by JayVora-SerpentCS** [comment]
@gregory-moka would be great if there is a PR! We can give a credit to you.
Thanks.

**Comment by mohil24** [comment]
Please check #433

**Comment by mohil24** [comment]
#433
