### ISSUE TITLE
Project Team vs. Project Privacy

### ISSUE THREAD

**Issue by sm2x** [JayVora-SerpentCS/SerpentCS_Contributions-v8#330]
What is the relationship between setting the Project's Team and Project Privacy Settings?
I set the privacy to "Invitation Only", and tried to log in a user who belongs to the projet's Team, but did not see the project.  Obviously, if I set the privacy to "Visible by all employees", everyone can see the project even if the user is not a member of the project's Team.  Is there any way that the Privacy respects the project's Team Members?

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs

**Comment by hpatelserpentcs** [comment]
Hello @sm2x ,

Thanks for Reporting this to us.

There is no relationship between  `Project's Team` and `Privacy`.
Project's Team is to manage Project Members (Inside Project), It is not Related to Project visibility for those members.
`Privacy` is for Visibility of that Project based on the Option (Not related to Members of Project team.)

> Is there any way that the Privacy respects the project's Team Members?

You can add record rule for `project.project` based on field `members`.

Thanks
