### ISSUE TITLE
web_groupby_expand v12

### ISSUE THREAD

**Issue by tsabi** [JayVora-SerpentCS/SerpentCS_Contributions-v8#336]
If i install the web_groupby_expand module into v12, a problem appears: if i click into a field in an embedded list in a form or wizard (for example in the password change wizard i click into the new password field) it opens the record of that line in a new window.
This is sometimes good, just like with invoice line, but sometimes it makes impossible the work, like the password change wizard (because the wizard_id is a required field but it is not filled).
If you want i can make a video.

**Comment by tsabi** [comment]
This is the same issue what miguel reported here: https://www.odoo.com/apps/modules/12.0/web_groupby_expand/

**Comment by hpatelserpentcs** [comment]
@maitree-serpentcs please check it.

**Comment by JayVora-SerpentCS** [comment]
Thanks!
