### ISSUE TITLE
[V11] sales_report_product_image (product image variant)

### ISSUE THREAD

**Issue by MiguelMachadoM** [JayVora-SerpentCS/SerpentCS_Contributions-v8#338]
Hello,

I have a problem with ODOO V11 website_sale, is a rare thing, my problem is flollowing:

When I change Quantity in website sale product from the image of product reduced to 64x64px.

I dont use product variant, but when I create a new Quotation or Order the image save in ir_attachemnt as image_variant (small in this case).

The problem, in you go to shop your product image get this image 64x64px, and no correct image, you can see this if active multi-image, and other problem,  you can activate product_variant and try delete this image from variant, you cant it.

I Solved delete all product.product and image variant from ir_attachment table. 
I think the problem is here: (but im not expert developer)

sales_report_product_image/models/sale_product.py

```
class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    image_small = fields.Binary(
'Product Image', related='product_id.image_small')
```

Regards,

**Comment by JayVora-SerpentCS** [comment]
cc @JagdishPanchalSCS

**Comment by JagdishPanchalSCS** [comment]
@MiguelMachadoM 

we have followed steps that you have provided but can't able to replicate the issue in our local system, can you please provide a video or a screen-shot so we can replicate the issue in our local system.

**Comment by MiguelMachadoM** [comment]
@JagdishPanchalSCS 

Install module web_tree_image
uncomment following lines:

sales_report_product_image/views/sale_product_view.xml

![imagen](https://user-images.githubusercontent.com/7348561/57465506-0ca40680-727f-11e9-947e-97f150eaa8d1.png)

and 

![imagen](https://user-images.githubusercontent.com/7348561/57465582-34936a00-727f-11e9-8475-f3ac5150c89c.png)

**Comment by JagdishPanchalSCS** [comment]
@MiguelMachadoM 

We have uncommented code and followed the same step, set product multi-image and product image also changed qty from the shop but its show proper size image.

In sale order line Product Image field should be small because if we add a big size image then it will not display proper view. 

But still, you have an issue please provide screenshot or video so we can check it and rectify your problem.

**Comment by JagdishPanchalSCS** [comment]
@MiguelMachadoM 
Can you please restest and let us know its work for you or not?

**Comment by JayVora-SerpentCS** [comment]
Seems it is working!
Closing henceforth, do reopen if you still face the issues.
Thanks.
