### ISSUE TITLE
[v12] Multiple One2many fields not working in web_kanban_one2many

### ISSUE THREAD

**Issue by sahil-navadiya** [JayVora-SerpentCS/SerpentCS_Contributions-v8#345]
if in kanban there is only one ONE2MANY fields then it will work but if we use multiple ON2MANY fields then it will render only one fields data. 

Check this screen video and let me know where is error. 

https://www.screencast.com/t/zJdbFQGnP 

Thank you.

**Comment by JayVora-SerpentCS** [comment]
@parvezqureshi

**Comment by JayVora-SerpentCS** [comment]
Closing it as its solved.
