### ISSUE TITLE
[10.0 ENT] Does not work with already grouped views 

### ISSUE THREAD

**Issue by PauliusP17** [JayVora-SerpentCS/SerpentCS_Contributions-v8#346]
Only tested on enterprise, but it would not be wrong to assume it's the same on CE.

When you open a view that is already grouped (take Inventory > Reports > Inventory Valuation for example which is grouped by product on opening it) the expand all icon does not show. However, if you switch to another view via the view manager and then back to the already grouped tree view (UPDATE: or even click the same tree view icon) it shows.

**Comment by JayVora-SerpentCS** [comment]
@parvezqureshi

**Comment by SerpentCS** [comment]
[FIX]Fixed the issue of web group by expand not work with already grouped views. #352
