### ISSUE TITLE
Mass Label Reporting : Font Size

### ISSUE THREAD

**Issue by DukeII** [JayVora-SerpentCS/SerpentCS_Contributions-v8#347]
Hi
When creating new label (Type : Normal) ... there is field " Font Size "
but using differend values doesn't have any effect when printing

any idea or is it possible to have this working in this module ?

best regards

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS Over to you!

**Comment by Chandresh-SerpentCS** [comment]
@DukeII Please mention that which odoo version are you using?

**Comment by DukeII** [comment]
@Chandresh Odoo11 or 12

**Comment by Chandresh-SerpentCS** [comment]
We will check and update to you on same.

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS is this supposed to closed now?
Thanks.

**Comment by Chandresh-SerpentCS** [comment]
@JayVora-SerpentCS #371 & #372 are the solution of the font size issue for 12.0 and 11.0 respectively.
