### ISSUE TITLE
web_menu freeze, how to clean uninstall

### ISSUE THREAD

**Issue by rtfmpliz** [JayVora-SerpentCS/SerpentCS_Contributions-v8#35]
Hi @JayVora-SerpentCS 

after install web_menu v8 for odoo v9, (my mistake) , 
It has symbol << but it is no respond even if it's clicked 
so i cant access to all bold menu (like apps in the left menu), position above Apps).
after I uninstall the web_menu module, the  << symbol is not dissapear

please help

thanks

wahyu

![screenshot from 2015-12-29 19 42 35](https://cloud.githubusercontent.com/assets/9409853/12034513/6531af2e-ae64-11e5-9e3b-47311b3e8aae.png)

**Comment by JayVora-SerpentCS** [comment]
Checking it at the earliest possible!

**Comment by JayVora-SerpentCS** [comment]
It seems its the concern with version incompatability. We would appreciate if you inform us in case the problem persists. We will fix it.
