### ISSUE TITLE
Error installing website_product_brand on Odoo.sh ver 12 by clicking "Deploy on Odoo.sh" button

### ISSUE THREAD

**Issue by elementsdistro** [JayVora-SerpentCS/SerpentCS_Contributions-v8#350]
Date | Level | Type | Message
-- | -- | -- | --
06/29/2019 00:30:02 | ERROR | server | Module website_sale: 1 failures, 0 errors
06/29/2019 00:30:02 | ERROR | server | FAILED
06/29/2019 00:30:02 | ERROR | server | ` AssertionError: False is not true : The test code "odoo.__DEBUG__.services['web_tour.tour'].run('shop_customize')" failed
06/29/2019 00:30:02 | ERROR | server | `     self.assertTrue(self.browser._wait_code_ok(code, timeout), message)
06/29/2019 00:30:02 | ERROR | server | `   File "/home/odoo/src/odoo/odoo/tests/common.py", line 928, in browser_js
06/29/2019 00:30:02 | ERROR | server | `     self.phantom_js("/", "odoo.__DEBUG__.services['web_tour.tour'].run('shop_customize')", "odoo.__DEBUG__.services['web_tour.tour'].tours.shop_customize.ready", login="admin")
06/29/2019 00:30:02 | ERROR | server | `   File "/home/odoo/src/odoo/addons/website_sale/tests/test_customize.py", line 45, in test_01_admin_shop_customize_tour
06/29/2019 00:30:02 | ERROR | server | Traceback (most recent call last):
06/29/2019 00:30:02 | ERROR | server | FAIL: test_01_admin_shop_customize_tour (odoo.addons.website_sale.tests.test_customize.TestUi)
06/29/2019 00:29:15 | ERROR | server | FAIL
06/29/2019 00:29:15 | ERROR | server | Script timeout exceeded : 60.00059247016907
06/29/2019 00:28:20 | ERROR | server | 500 Internal Server Error:  Traceback (most recent call last):   File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch     result = request.dispatch()   File "/home/odoo/src/odoo/odoo/http.py", line 835, in dispatch     r = self._call_function(**self.params)   File "/home/odoo/src/odoo/odoo/http.py", line 346, in _call_function     return checked_call(self.db, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper     return f(dbname, *args, **kwargs)   File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call     result = self.endpoint(*a, **kw)   File "/home/odoo/src/odoo/odoo/http.py", line 941, in __call__     return self.method(*args, **kw)   File "/home/odoo/src/odoo/odoo/http.py", line 519, in response_wrap     response = f(*args, **kw)   File "/home/odoo/src/user/website_product_brand/controllers/main.py", line 33, in shop     attrib_set = set([v[1] for v in attrib_values])   File "/home/odoo/src/user/website_product_brand/controllers/main.py", line 33, in <listcomp>     attrib_set = set([v[1] for v in attrib_values]) TypeError: 'map' object is not subscriptable

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs please take a look.

**Comment by hpatelserpentcs** [comment]
@JayVora-SerpentCS 

I will check it.

**Comment by hpatelserpentcs** [comment]
@JayVora-SerpentCS @elementsdistro 
Solved in #351
