### ISSUE TITLE
base_synchro odoo 10 error object unbound

### ISSUE THREAD

**Issue by MartianX** [JayVora-SerpentCS/SerpentCS_Contributions-v8#353]
Hello 
i'm trying to synchronize 2 different odoo hosted on different servers but when i try to synchronize i get this error:
WARNING db_sync odoo.addons.base_synchro.wizard.base_synchro: Synchronize will be skipped because of
            error <Fault object unbound: 'Traceback (most recent call last):\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/http.py", line 118, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/service/common.py", line 57, in dispatch\n    return g[exp_method_name](*params)\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/service/common.py", line 23, in exp_login\n    res = security.login(db, login, password)\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/service/security.py", line 9, in login\n    return res_users._login(db, login, password)\n  File "/home/odoo/eclipse-workspace/odoo/odoo-10.0/odoo/addons/base/res/res_users.py", line 470, in _login\n    user.sudo(user_id).check_credentials(password)\n  File "/home/odoo/odoo-dev/addons_allpharma/login_user_detail/models/login_user_details.py", line 39, in check_credentials\n    ip_address = request.httprequest.environ[\'REMOTE_ADDR\']\n  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__\n    return getattr(self._get_current_object(), name)\n  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object\n    return self.__local()\n

**Comment by JayVora-SerpentCS** [comment]
@Chanakya-SerpentCS

**Comment by Chanakya-SerpentCS** [comment]
Hello @MartianX,

I have tested this module again in my local system it is working for me.
Can you please explain us little more how to reproduce this issue.

(Initially, from the log provided by you, I can say that it might be the issue of login_user_detail module)

But still if you think it may be issue of base_synchro module then please guide us how to replicate this issue in our environment.

Thanks

**Comment by MartianX** [comment]
Hello @Chanakya-SerpentCS, 
thanks for your replay and yes by removing the module " login_user_detail " from the distant server i was able to start the synchronization 
Thanks.
