### ISSUE TITLE
sync error with modul sync multi database odoo 12

### ISSUE THREAD

**Issue by dionarya111** [JayVora-SerpentCS/SerpentCS_Contributions-v8#356]
i try the modul of synchronize multi database in odoo 12.
i get the error when i set 2 database. one in my server and one in my PC.  (the 2 of them using one connection).
my PC using IP 192.168.200.112, and the server using IP 192.168.200.181.  when i set in server, i set the server URL is : 192.168.200.112
then in my PC server URL is : 192.168.200.181

but it's not connect and get error.
please cann help me?

**Comment by JayVora-SerpentCS** [comment]
@swapnesh-serpentcs

**Comment by Swapnesh-SerpentCS** [comment]
Hello @dionarya111  
Can you please add some details on How to reproduce it/ or Some error log with screenshots?

**Comment by JayVora-SerpentCS** [comment]
@dionarya111 can you please test with the latest source?
