### ISSUE TITLE
[12.0]Error xpath "product_extended"

### ISSUE THREAD

**Issue by Manuel-Dellisse** [JayVora-SerpentCS/SerpentCS_Contributions-v8#357]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/blob/eaf944a08eb27e8d9d65e79be428db11a37d5975/website_multi_image_zoom/views/templates.xml#L29

Div with class "col-sm-7" does not seem to exist in "website_sale.product" on Odoo v12.
With a quick comparison I suspect that the corresponding block is the div with class "col-md-6" from the 2nd div with class "row".

![image](https://user-images.githubusercontent.com/6159662/62048270-bbb40680-b20c-11e9-9cc4-826fbeda7aa8.png)

**Comment by katiakweb** [comment]
> https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/blob/eaf944a08eb27e8d9d65e79be428db11a37d5975/website_multi_image_zoom/views/templates.xml#L29
> 
> Div with class "col-sm-7" does not seem to exist in "website_sale.product" on Odoo v12.
> With a quick comparison I suspect that the corresponding block is the div with class "col-md-6" from the 2nd div with class "row".
> 
> ![image](https://user-images.githubusercontent.com/6159662/62048270-bbb40680-b20c-11e9-9cc4-826fbeda7aa8.png)

Do you fix it? How?

**Comment by JayVora-SerpentCS** [comment]
@chiragpatel-serpentcs

**Comment by ChiragPatel-SerpentCS** [comment]
@Manuel-Dellisse @katiakweb Added Fix at https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/359

**Comment by katiakweb** [comment]
> @Manuel-Dellisse @katiakweb Added Fix at #359

Thanks! :+1:
