### ISSUE TITLE
no work on mobile view

### ISSUE THREAD

**Issue by agentemotor** [JayVora-SerpentCS/SerpentCS_Contributions-v8#358]
I have add this code on the sales order kanban view.

` <t t-foreach="record.order_line.raw_value" t-as="o">
          <div class="o_kanban_image" style="width: 60;height: 30;">
              <img t-att-src="kanban_image('product.template', 'image_small', o.product_id)" alt="Logo"/>
           </div>
            <t t-esc="o.name"/>
  </t>`

This work fine when i access from PC, but when i access form a mobile, this fields are no displayed.

**Comment by JayVora-SerpentCS** [comment]
@parvezqureshi Take a look plz.
