### ISSUE TITLE
Change with web_tree_image_tooltip

### ISSUE THREAD

**Issue by Crisa221** [JayVora-SerpentCS/SerpentCS_Contributions-v8#361]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/blob/62cf51218e232fdf65bd11324997f4398019ca65/sales_report_product_image/__manifest__.py#L14

You have to change the name of the depends in the manifest because from version 12 it's called web_tree_image_tooltip
Official OCA PR link: https://github.com/OCA/web/pull/1100/files#diff-a903cfff97438d4f6bd43cc8d94fbaba

**Comment by JayVora-SerpentCS** [comment]
Perfect, thanks.

**Comment by Crisa221** [comment]
Hi, I wanted to know if the module was built? In case it was done can you tell me? Thank you!

**Comment by JayVora-SerpentCS** [comment]
@Crisa221 here is the module FYI https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/tree/12.0/sales_report_product_image
