### ISSUE TITLE
currentTopic[i] is undefined. web_digital_sign module

### ISSUE THREAD

**Issue by JKSithu** [JayVora-SerpentCS/SerpentCS_Contributions-v8#366]
After reload the page, then zoom in/out page showed that error on odoo 10.
![image](https://user-images.githubusercontent.com/47236725/63332061-e5200800-c35c-11e9-8feb-c6bbf8c02bfd.png)

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs

**Comment by hpatelserpentcs** [comment]
@drashtipatel24 
Please check issue

CC @maitree-serpentcs

**Comment by drashtipatel24** [comment]
@JKSithu  I have fixed the issue. #368
