### ISSUE TITLE
web_widget_multi_image 

### ISSUE THREAD

**Issue by ghost** [JayVora-SerpentCS/SerpentCS_Contributions-v8#38]
trying to use web_widget_multi_image on Odoo v9.0 but gives me an error on the browser console 

error: Some modules could not be started        web.assets_common.js:2523

**Comment by ghost** [comment]
Need some help on this module, Please!!!!

**Comment by JayVora-SerpentCS** [comment]
@Mohamed-Alaa The commit bd05a8c44014c0ca8073125d76be7d047c815134 Fixes it.
