### ISSUE TITLE
[after installing on odoo V11-ce] Web Lead Funnel Chart

### ISSUE THREAD

**Issue by ajit-radometech** [JayVora-SerpentCS/SerpentCS_Contributions-v8#389]
when click on Funnel Chart in CRM module
Action Error
Could not find client action 'web_lead_funnel_chart.funnel'.
is displayed in pop-up

**Comment by JayVora-SerpentCS** [comment]
@nikitavaghela

**Comment by nikitavaghela** [comment]
Hello @ajit-radometech,
I tested this module in a new database. I didn't get any error. so can you please list out steps or show me an issue in the video. so I can check the exact issue.

**Comment by Savitri-SerpentCS** [comment]
I have checked this one and I'm not able to Reproduce this issue too.

@JayVora-SerpentCS  We can close this one.
