### ISSUE TITLE
project_team - remove user from team template deletes the user from the system

### ISSUE THREAD

**Issue by gezzzan** [JayVora-SerpentCS/SerpentCS_Contributions-v8#39]
When removing a user from a Project team "template", it deletes the user completely from the system

It is happening when using the view where you can prepare teams with members that can be used later for various projects. The view for managing team members inside a given project is fine.

To reproduce: create a new project team, add a new member, save it. Than edit the team, remove the user, save the team. Check Settings->Users, the removed user is deleted from the system.

Odoo version: Version 9.0c-20160115 (Community Edition) 
project_team addon version: 9.0.1.0.0

I attached screenshot about it

thanks for looking into this,
cheers,
gezza

![odoo_project_team_addon_error](https://cloud.githubusercontent.com/assets/13525746/12374514/b881bc72-bc9d-11e5-8afc-716ef381c67e.png)

**Comment by JayVora-SerpentCS** [comment]
@gezzzan This is a design fault in Odoo9. Members have been used in Teams as One2many while we should have it as M2M. I will correct and revert.
