### ISSUE TITLE
[web_groupby_expand 12.0]: Button is not render if there only one view

### ISSUE THREAD

**Issue by Kontrolix** [JayVora-SerpentCS/SerpentCS_Contributions-v8#391]
If i have only one view of type list, I would like that the button "Expand" appear. But it doesn't show up and i suspect that this code is reponsible of the problem:

```
_renderSwitchButtons: function () {
    var self = this;
    var views = _.filter(this.actionViews, {multiRecord: this.isMultiRecord});
    
    if (views.length <= 1) {
        return $();
    }
[...]
```

It came from Odoo addon: web\static\src\js\views\abstract_controller.js line 378

Hope you could find a workaround, that would be great

**Comment by JayVora-SerpentCS** [comment]
@nikitavaghela

**Comment by Kontrolix** [comment]
@drashtipatel24 solution does the job for me.

**Comment by drashtipatel24** [comment]
Glad to hear that and thank you for the update.
