### ISSUE TITLE
Partner Credit Limit v12 : Consider Adv payment case

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#413]
Reported by:
James

Details:
Customer Credit limit = 0.00
Payment Terms = Proforma

Order value = 100

Customer pays 100 in advance so you record a payment in accounting, this allows the sales order to be confirmed.

You cannot now process a delivery order? You get the same warning message from sale.order - despite the amount showing correctly registered on the customer.

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS we can have Pratik take a look.

**Comment by PratikVaza-SerpentCS** [comment]
@JayVora-SerpentCS Sir, 
This issue was fixed. I just took the latest pull and tested with fresh database for version 12.0
(FIxed the issue through this PR: https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/547) 
Thanks.
