### ISSUE TITLE
partner_credit_limit does not account for different invoice amounts

### ISSUE THREAD

**Issue by travish2** [JayVora-SerpentCS/SerpentCS_Contributions-v8#417]
Using v12, partner_credit_limit/models/sale.py

The code in partner_credit_limit assumes that _amount_total_ from the sales orders and _debit_ from account move lines will be the same amount when calculating _available_credit_limit_ and in deciding whether to block the sale.

This will not be correct if the customer has had additional charges or discounts on an invoice that is not also on a sales order, eg. late payment charges

To address this I added the following to check_limit():
```
            saleline_obj = self.env['sale.order.line']
            salelines = saleline_obj.search(
                [('order_partner_id', '=', partner.id),
                 ('state', '=', 'sale'),
                 ('invoice_status', '=', 'to invoice'), ]
            )

            uninvoiced_sales = 0.0
            for line in salelines:
                uninvoiced_sales += line.price_reduce_taxinc * line.qty_to_invoice
            #This sales order is included from above calculation, remove it:
            uninvoiced_sales = uninvoiced_sales - self.amount_total
```

and changed this logic:
```
            available_credit_limit = \
                ((partner_credit_limit -
                  (amount_total - debit)) + self.amount_total)


            if (amount_total - debit) > partner_credit_limit:
```
to:
```
            available_credit_limit = (partner_credit_limit - uninvoiced_sales)

            if self.amount_total > available_credit_limit:
```

I believe you can remove the amount_total and confirm_sale_order portion of code also

**Comment by murtuzasaleh** [comment]
@travish2 We will check it and update you.

**Comment by tanzilbs23** [comment]
@travish2 I think there is a problem where you are removing the current sale order amount.

```
#This sales order is included from above calculation, remove it:
uninvoiced_sales = uninvoiced_sales - self.amount_total
```

The check_limit is triggered when the action_confirm() button is clicked, which means current SO is in draft (Quotation) state. This is not included in your saleslines list. 

Let's say, you have a customer who has 5000 as credit limit. If you create a sale order for 6000 and click on the confirm button, the saleslines will give you -6000, as you are deducting the amount which is not on the list.

It's not needed, I think?

**Comment by travish2** [comment]
@tanzilbs23 You are right logically it should not be included there however on my instance it is for some reason I have not had time to dig into.

Eg a customer has $2000 credit limit and $200 sales -- when I create quotation for $3000 and click Confirm the alert says the customer has $1800 credit limit left.

**Comment by tanzilbs23** [comment]
@travish2 You must have some other logic implemented. Like - 

Your first uninvoiced_sales is = 500 (sale and to invoice state)
current saleorder amount_total is = 1000 (draft state)

so your final uninvoiced_sales = 500 -1000 = - 500

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS Check well with Deepak.

**Comment by JayVora-SerpentCS** [comment]
this should be sorrted with latest push, thanks.
