### ISSUE TITLE
DOES NOT PRINT IMAGE

### ISSUE THREAD

**Issue by CarlosROFA** [JayVora-SerpentCS/SerpentCS_Contributions-v8#418]
I installed your module, but it does not print the image on the label.
I have ODOO V12 COMUNITY i server
I installed: 
sudo pip install pyBarcode
sudo pip install utils 
sudo pip install cairosvg 
too installed:
sudo pip3 install pyBarcode 
sudo pip3 install utils 
sudo pip3 install cairosvg 

When I configure the label I add the image field image medium product.template, instead of printing the photo, print a small empty square.

Thanks

**Comment by CarlosROFA** [comment]
It is in module: Mass Label Reporting

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS

**Comment by Savitri-SerpentCS** [comment]
Hello @CarlosROFA 
Thanks for Reporting Issue.

I am able to Reproduce this issue and We will have a follow-up on this soon.

**Comment by travish2** [comment]
report/dynamic_label.xml

Change line 29 from:
`<img t-att-src="'data:image/png;base64,%s' % (val.get('value'))"`

to:
`<img t-att-src="'data:image/png;base64,%s' % to_text(val.get('value'))"`

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS can you plz verify ?

**Comment by Chandresh-SerpentCS** [comment]
#424 Fixed.
