### ISSUE TITLE
Blank page after copying files (v9)

### ISSUE THREAD

**Issue by romainl63** [JayVora-SerpentCS/SerpentCS_Contributions-v8#42]
I copied the file extension, install the two python libraries, reboot the Odoo serveur.
When charging, the menu is blank, there is no error in the log file.
I did not even install the extension. If I remove files from my add-on folder, all works again.
![odoo-blank](https://cloud.githubusercontent.com/assets/10233399/13179035/380c9234-d722-11e5-96aa-fabe5eaa8774.jpg)

**Comment by JayVora-SerpentCS** [comment]
Which files/modules did you copy?

**Comment by romainl63** [comment]
The module from Odoo website, file "label-9.0.1.0.0.zip"
https://www.odoo.com/apps/modules/9.0/label/

I followed the usual procedure to install a module

**Comment by mikes-techzone** [comment]
I have the same issue with both from git and from the Odoo website

**Comment by mikes-techzone** [comment]
I switch from all in one windows installer to source install on windows. now works all and I solved the problem
