### ISSUE TITLE
Multi-DB Synchronization Issue v11 - Fleet

### ISSUE THREAD

**Issue by mosaabdulali** [JayVora-SerpentCS/SerpentCS_Contributions-v8#422]
Greetings,

I tried Multi-DB Synchronization module for version 11 for database syncronization but it failed.
It worked fine for Vehicle basic information but not for others e.g. Vehicle Contracts, Vehicle Fuel Logs .... etc.
I got this message **_“Emptying the odometer value of a vehicle is not allowed.”_**
All my testing was done to synchronize from clean database with Odoo standard demo data only to clean database.

Looking for your support.

**Comment by JayVora-SerpentCS** [comment]
@mosaabdulali This error is a constraint warning. So the data is rightly getting in, its just the constraint that fails. Check what you sync, odometer should not have zero value.

**Comment by mosaabdulali** [comment]
@JayVora-SerpentCS 
Some of the cost items will never get odometer value as there is no entry for it in frontend.

<img width="1152" alt="CleanShot 2020-03-12 at 10 24 34@2x" src="https://user-images.githubusercontent.com/34865819/76497288-c3e34e00-644b-11ea-8435-e27d97b9a6a4.png">

That is where it is failed & as I said before my testing was done for **Odoo demo data**.
