### ISSUE TITLE
Partner Credit Limit not restricting sales order confirmation

### ISSUE THREAD

**Issue by dotman77** [JayVora-SerpentCS/SerpentCS_Contributions-v8#425]
After installing Partner Credit Limit in Odoo 10, I set a customer's credit limit to 1,000,000. The customer previously had a Total Receivable of 573,645.

After disabling the "Allow Over Credit?" checkbox, I was still able to confirm a sale order for 1,700,000 which should not be possible.

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS We did for one proj together in last assignment with Deepak. check with him so we can put this in TODO and finish.
Thank you.

**Comment by Chandresh-SerpentCS** [comment]
Noted.

**Comment by Chandresh-SerpentCS** [comment]
@dotman77 We are not able to find any issue to confirm the sale order with/without set the credit limit in customer. Hope you have the latest code in your instance. Let me know if you have still any doubt or any concern. Thanks !
