### ISSUE TITLE
[9.0] Label: No Configuration For Paper Format/Size

### ISSUE THREAD

**Issue by lukebranch** [JayVora-SerpentCS/SerpentCS_Contributions-v8#44]
@JayVora-SerpentCS ,

Thank you for building another very useful module!

I'm interested in using this module for printing labels from a label printer, specifically one with the label size:

101.6mm Wide x 76.2mm High

however I cannot find a configuration area where I can define the size of the paper that the labels are printed on (ie. Paper Format in regular Odoo).

I've found a way to edit the paper size of the label.report_label report to make it use my own paper size (101.6mm W x 76.2mm H) instead of the default (European A4), however this only seems to stretch (or rather squeeze) the label width so that the there is still two labels per row, which is not the desired behaviour.

What I would like to do is have each label measuring around 101mm x 76mm to print in a stack, vertically, one on top of the other like most label printers do (eg. from a roll of labels).

Is there a configuration setting that i'm not seeing that can achieve this behaviour with the module out of the box, or do I need to modify the code to achieve what I want to do?

**Comment by odaybari** [comment]
hi 

how did you corrected the importerror when installing. 

` "/odoo/custom/addons/label/__init__.py", line 4, in <module>
    from . import models
ImportError: cannot import name models`

Thanks

**Comment by Chandresh-SerpentCS** [comment]
@lukebranch, For now, the solution is to edit the A4 paper format. We invite contributions n PR from you, much appreciated.

@odaybari, the error doesn't happen to anyone by far. I suspect, this could be due to version indifference, i.e. odoo8 with label 9.

Kindly check and revert.
Thanks.
