### ISSUE TITLE
[7.0] Error installing web_groupby_expand

### ISSUE THREAD

**Issue by gbonline** [JayVora-SerpentCS/SerpentCS_Contributions-v8#46]
Hi, I'm trying to test your addon web_groupby_expand on Openerp 7, but I can't install it, i get the error:

`AssertionError: Did not expect element template there, line 6`

the file views/templates.xml
have the tag < template > that openerp don't like

What can i Do?
G.

**Comment by ghost** [comment]
Hello @gbonline 

We will check the issue and will update you asap.

Thanks.

**Comment by manamirfhk** [comment]
Hi, I encountered the same issue.
I expect your update, thanks.

**Comment by Roodin** [comment]
Any new about this?

**Comment by JayVora-SerpentCS** [comment]
It's a WIP
