### ISSUE TITLE
"sales_report_product_image" image variant issue

### ISSUE THREAD

**Issue by MiguelMachadoM** [JayVora-SerpentCS/SerpentCS_Contributions-v8#48]
Images and Variants.

Im not sure but can try it. Test whether the same problem occurs

My problem when I create a sale order and use small image this modify image from Product variant and when you see this product on shop show small image.

I move to products variants, and when see image is small. My solution:

on models/sale_product.py add  **readonly=True**

```
class sale_order_line(models.Model):
    _inherit = 'sale.order.line'

    image_small = fields.Binary(string='Product Image',
                                related='product_id.image_small', readonly=True)
```

**Comment by JayVora-SerpentCS** [comment]
usually image_X field should be a function field.
