### ISSUE TITLE
Image distorted in printing pdf report with Product Image for Sale module

### ISSUE THREAD

**Issue by Joe-Karusindo** [JayVora-SerpentCS/SerpentCS_Contributions-v8#484]
I have installed the Product Image for Sale module. Printing the quotation pdf report shows the image distorted. Please kindly advise. Thank you.
<img width="815" alt="Screen Shot 2020-07-18 at 23 37 05" src="https://user-images.githubusercontent.com/68475518/87857278-a5d4af80-c94f-11ea-9b8d-8baf0c39458c.png">

**Comment by JayVora-SerpentCS** [comment]
@JadavVishal-SerpentCS 





Type a message

**Comment by Joe-Karusindo** [comment]
I have installed the Product Image for Sale module. Printing the quotation pdf report shows the image distorted. Please kindly advise. Thank you.

**Comment by JadavVishal-SerpentCS** [comment]
@Joe-Karusindo we will check and update you

**Comment by Joe-Karusindo** [comment]
OK. Look forward to

**Comment by Joe-Karusindo** [comment]
Thank you for fixing it but still the image is distorted when printing the quotation in PDF format. Please see the screen shot provided:
<img width="761" alt="Screen Shot 2020-07-23 at 22 22 25" src="https://user-images.githubusercontent.com/68475518/88305123-54536880-cd33-11ea-8d62-cb5801568bf7.png">
