### ISSUE TITLE
Web Security Dialog v13.0: Wrong Spelling on Password popup.

### ISSUE THREAD

**Issue by poonam-serpentcs** [JayVora-SerpentCS/SerpentCS_Contributions-v8#489]
https://prnt.sc/tn1ps3

**Comment by hpatelserpentcs** [comment]
@poonam-serpentcs

It displays properly, see in below image
![image](https://user-images.githubusercontent.com/26454900/90248526-7b92e680-de56-11ea-9502-2a6e2ccca9a4.png)

**Comment by poonam-serpentcs** [comment]
I have tried again and it is still wrong
![screenshot-localhost_8069-2020 08 17-10_36_32](https://user-images.githubusercontent.com/51950448/90359108-9becbc00-e075-11ea-8a35-553c78d08f36.png)


Created a new Database
Installed Web Security Dialog and CRM Module
Edited form view and added Option `confirm="message" options='{"security":"security_field"}'`
![screenshot-localhost_8069-2020 08 17-10_38_42](https://user-images.githubusercontent.com/51950448/90359200-dbb3a380-e075-11ea-82e9-1344be6d8bdd.png)

**Comment by tushar-serpentcs** [comment]
Issue fixed https://prnt.sc/1s5qbau

**Comment by poonam-serpentcs** [comment]
Issue has been fixed.
