### ISSUE TITLE
Image distorted in printing pdf report with Product Image for Sale module by Serpent Consulting Service

### ISSUE THREAD

**Issue by Joe-Karusindo** [JayVora-SerpentCS/SerpentCS_Contributions-v8#492]
Thank you for fixing it but still the image is distorted when printing the quotation in PDF format. Please see the screen shot provided:
<img width="761" alt="Screen Shot 2020-07-23 at 22 22 25" src="https://user-images.githubusercontent.com/68475518/88357070-310cd580-cd94-11ea-88fe-c26b5fb7cfe8.png">

**Comment by JayVora-SerpentCS** [comment]
@JadavVishal-SerpentCS can you see?

**Comment by Joe-Karusindo** [comment]
Sorry, what do you mean? The distortion? yes it is distorted as above picture. In fact I was printing small image. With medium and large images, distortion is worse.

**Comment by JayVora-SerpentCS** [comment]
@JadavVishal-SerpentCS Please respond.

**Comment by sompheng** [comment]
I have the same problem:
I run Odoo 13 community on Ubuntu 20.04 
Have the same problem on product’s pictures not on the right scale

**Comment by JadavVishal-SerpentCS** [comment]
@Joe-Karusindo @sompheng Image distortion may be effect due to wkhtmaltopdf version.

**Comment by sompheng** [comment]
Which version of WHTMLtoPDF version you recommended? (For Ubuntu 20.04 , odoo13 community)

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/548 fixed.
