### ISSUE TITLE
Partner Credit Limit

### ISSUE THREAD

**Issue by sammi-vkd** [JayVora-SerpentCS/SerpentCS_Contributions-v8#523]
We are experiencing challenges with the credit limit feature and the calculation of available limit.
 
1.	Customer has a credit limit of 200,000 DKK, which is created on the customer:
![cre](https://user-images.githubusercontent.com/61730334/101366088-d5576a80-38a4-11eb-92bd-27e5c774a998.png)

2.	Outstanding balance before new sales order is DKK 75,532.50, This means that there should be an available limit of (200,000-75,532.50) 124,467.50 DKK
![cre1](https://user-images.githubusercontent.com/61730334/101366135-dee0d280-38a4-11eb-9167-6706f905ad9d.png)

3) We create a sales order of 37,766.25 DKK, but when we try to confirm the order the following error message comes:
![cre2](https://user-images.githubusercontent.com/61730334/101366174-ea33fe00-38a4-11eb-9875-23ca937cdd10.png)

Since the available credit limit should have been $ 124,467.50, there should be plenty of room for this sales order.
 
Based on the information in the error message about an "available limit of DKK 29,829.12", it fits with the difference between the set credit limit of DKK 200,000 and the total sales to this customer of DKK 170,170.88. It therefore suggests that the system looks at the wrong balance when calculating the available credit amount - that is, it uses the total balance for the entire period and not the current balance after payments have been made.
 
4) To push the order through, we have had to put a tick in "Allow Over credit" on the customer. Once we have done that, the order can be executed, but at the same time the system changes the registered credit limit from DKK 200,000 to DKK 37,766.25. What caused it?

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS will take a look.
Thanks.

**Comment by sammi-vkd** [comment]
Any news

**Comment by Chandresh-SerpentCS** [comment]
@sammi-vkd I will give you an update on next week.

**Comment by sammi-vkd** [comment]
Our customer really needs a solution on this issue, can you please give us an update

**Comment by Chandresh-SerpentCS** [comment]
We are working on it to fix/improve the module code. You will get an update.

**Comment by Freni-SerpentCS** [comment]
@sammi-vkd Fixed it. According to the current feature, Customer can make total orders within the credit limit.
future scope: paid order amount will be removed from the credit limit.

**Comment by sammi-vkd** [comment]
Can we get the update from Odoo Appstore?

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS will review and affirm, then we will push to appstore.
Thanks.

**Comment by sammi-vkd** [comment]
Can you please push to app store

**Comment by JayVora-SerpentCS** [comment]
pushed

**Comment by sammi-vkd** [comment]
Hi, we can't see the update in app stpre, but we can see that you made some changes in the Github code, but its still the same version.

Can you plese telle us where to get the correct update

**Comment by JayVora-SerpentCS** [comment]
The appstore is latest already : https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/tree/13.0/partner_credit_limit
