### ISSUE TITLE
Cannot Print out Many2One field on Mass Label Printing Module

### ISSUE THREAD

**Issue by Jirawatz** [JayVora-SerpentCS/SerpentCS_Contributions-v8#527]
I have tried to attempt to print out the shipping address and the delivery address from the Mass Label Printing Module, but it only prints me the user id instead of the complete address of the customer. I have noticed that the field that I choose is many2one type field, thus is there a way for me to print out the many2one type field?

**Comment by JayVora-SerpentCS** [comment]
Solved with latest commit.
