### ISSUE TITLE
[14.0_MIG_sale_report_product_image][Suggestion] : Multi select checkbox should be available in Search : Product wizard.So,User can select multiple products in single time.

### ISSUE THREAD

**Issue by Savitri-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#534]
@YogeshMahera-SerpentCS  Multi selection of products helps user when he/she wants to print multiple product images.It takes more time to select one by one images.

STEPS : 1. Go to Sales -> Sales Orders form view
               2. In Order Lines tab,Click on Add a product option and Observe in Search : Product wizard 

Attachment : https://prnt.sc/xp8hqs

**Comment by pragatipatel-serpentcs** [comment]
@Savitri-SerpentCS
please check your network connection if you are using a network that is with a firewall then it will show a security issue else not.

**Comment by YogeshMahera-SerpentCS** [comment]
It's odoo standard, no more required this enhancement.

**Comment by YogeshMahera-SerpentCS** [comment]
@Savitri-SerpentCS close this issue please

**Comment by Savitri-SerpentCS** [comment]
As per the developer's comment , this issue has been closed.
