### ISSUE TITLE
[14.0_MIG_sale_report_product_image][Issue] : UI is not looking proper in report when product image is not available.

### ISSUE THREAD

**Issue by Savitri-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#536]
@YogeshMahera-SerpentCS 

STEPS : 1. Go to Sales -> Sales Orders form view and Configure Image Sizes : Big sized Image and then observe in report.

Attachment : https://prnt.sc/xparu0

**Comment by pragatipatel-serpentcs** [comment]
@Savitri-SerpentCS 
The issue has been fixed.

Attachment: https://prnt.sc/z387fj

**Comment by Savitri-SerpentCS** [comment]
Resolved
