### ISSUE TITLE
[14.0_MIG_sale_report_product_image][Issue] : When Print Image field is checked true but Images size is not selected then Product image is not displaying in report.

### ISSUE THREAD

**Issue by Savitri-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#537]
@YogeshMahera-SerpentCS 

STEPS : 1. Go to Sales -> Sales Orders form view
               2. Check true of Print Image field
               3. Do not select any value in image sizes field and then print report

Attachment : 1. https://prnt.sc/xpcepg
                     2. https://prnt.sc/xpchhl

**Comment by pragatipatel-serpentcs** [comment]
@Savitri-SerpentCS 
The issue has been fixed.

**Comment by Savitri-SerpentCS** [comment]
Resolved
