### ISSUE TITLE
[14.0_MIG_sale_report_product_image][Issue] : Security issue displays when click event fires on Facebook,Twitter and Instagram icons.

### ISSUE THREAD

**Issue by Savitri-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#538]
@
Attachment : https://prnt.sc/zkfwbg

STEPS : 1. Open index file of sales_report_product_image
               2. Click on above mentioned icons

**Comment by YogeshMahera-SerpentCS** [comment]
@Savitri-SerpentCS 
please check your network connection if you are using a network that is with a firewall then it will show a security issue else not.

**Comment by pragatipatel-serpentcs** [comment]
@Savitri-SerpentCS
please check your network connection if you are using a network that is with a firewall then it will show a security issue else not.

**Comment by Savitri-SerpentCS** [comment]
I have checked with my own mobile network,it's working fine with it.Issue replicates only when office network is connected.So closing this issue.
