### ISSUE TITLE
Wishlist : partner_credit_limit due amount check

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [JayVora-SerpentCS/SerpentCS_Contributions-v8#540]
[Credit Limit Module.odt](https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/files/6544069/Credit.Limit.Module.odt)

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS Module awaited!

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS ?

**Comment by Chandresh-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/546
