### ISSUE TITLE
template['kanban-box']: No enumerator given to foreach , that's what i got when i loop into one2many field using on2many kanban module ??? it does nothing 

### ISSUE THREAD

**Issue by mostafaic** [JayVora-SerpentCS/SerpentCS_Contributions-v8#56]
when i use the module web_one2many kanban for odoo 0.8 i followed the descrbtion to use it to access the values of the one2many field but it does nothing with me using foreach

**Comment by JayVora-SerpentCS** [comment]
We have improved it for odoo10, can you please check?
