### ISSUE TITLE
[FIX] Errors in manage the repo (the way not the context)

### ISSUE THREAD

**Issue by nhomar** [JayVora-SerpentCS/SerpentCS_Contributions-v8#6]
Hello.

It should be cool if you propose your public repositories following OCA structure (even if they are not part of OCA) in that way we can make PR more efficiently).

i.e;: 
1. Have an 8.0 branch not a master.
2. Activate travis.
3. Activate Coverage.

We forked to use some of those tools, but it should be cool if I can propose our investment of time as PR and not mantain for ourself ;-)

Thanks for the contribution.

Regards.

**Comment by JayVora-SerpentCS** [comment]
We are now following this way already.
