### ISSUE TITLE
[9.0] web_one2many_kanban Appear id many2one

### ISSUE THREAD

**Issue by abdallamhafeez** [JayVora-SerpentCS/SerpentCS_Contributions-v8#61]
When create loop and write any field has type "many2one" in kanban view, It appear id and name as appear in picture in "stock.picking" kanban 
![picking](https://cloud.githubusercontent.com/assets/13385546/19459203/982fb8fe-94d1-11e6-9a97-dede5a0d07ca.PNG)

**Comment by sudhir-serpentcs** [comment]
Hi @abdallamohamed1992 for any many2one field you need to use it like this:
`<t-esc="o.product_id[1]"`/>

Here, o.product_id will be rendered and will call the **name_get** method and will return list of tuple **[(34, "[LAP-CUS] Laptop Customized")]** containing record id and its name / rec_name.

Hope this will solve your issue.
Thanks for your comment.
