### ISSUE TITLE
[9.0] web_one2many_kanban empty columns in any kanban

### ISSUE THREAD

**Issue by abdallamhafeez** [JayVora-SerpentCS/SerpentCS_Contributions-v8#62]
Hello
Please see below picture. There is empty column in every kanban in system after install this module 
web_one2many_kanban
![kanban error 2](https://cloud.githubusercontent.com/assets/13385546/19816186/9be0916c-9d46-11e6-9633-ea4195ad06e4.png)

![kanban error](https://cloud.githubusercontent.com/assets/13385546/19816012/c91a78d8-9d45-11e6-8e55-6b58493a0eeb.png)

**Comment by guohuadeng** [comment]
I got the same problem in odoo 10, also all the one2may value is empty.
Thanks.
![image](https://cloud.githubusercontent.com/assets/8255692/22579716/499ac544-ea0d-11e6-82c2-fdd6ee479a64.png)
=
![image](https://cloud.githubusercontent.com/assets/8255692/22579723/54e82ae0-ea0d-11e6-9d5e-d88c26d5a1df.png)

**Comment by sudhir-serpentcs** [comment]
@abdallamohamed1992 @guohuadeng Please check latest code we have fixed the issue.
Thanks for your support and interest.
