### ISSUE TITLE
base_module_record for version 10

### ISSUE THREAD

**Issue by augustosamame** [JayVora-SerpentCS/SerpentCS_Contributions-v8#65]
base_module_record appears on 10.0 branch but does not work. Will it be upgraded to v10.0 any time soon? I can help if you give me some pointers.

**Comment by JayVora-SerpentCS** [comment]
We are working on the v10. As its opensource, we would appreciate if you have your own contributuon towards it.
In case, you have a very personal need of it, we can expedite on commercial aspects.

**Comment by JayVora-SerpentCS** [comment]
We are working on the v10. As its opensource, we would appreciate if you have your own contributuon towards it.
In case, you have a very personal need of it, we can expedite on commercial aspects.

**Comment by JayVora-SerpentCS** [comment]
Please check latest v10 source.
