### ISSUE TITLE
web_groupby_expand - Odoo 9 CE with Material Backend Theme

### ISSUE THREAD

**Issue by cbjesse** [JayVora-SerpentCS/SerpentCS_Contributions-v8#67]
First of all it looks like the "src" folder is incomplete missing the js and xml files?
Secondly I tried copying these from version 8 and installed without any errors but it broke the whole theme the menu no longer worked. Any suggestions?

**Comment by sutanto62** [comment]
No web_groups_expand.js found.

**Comment by sudhir-serpentcs** [comment]
@cbjesse @sutanto62 Thanks for your comments.
Module is migrated now in v9 and it will work in both Community and Enterprise versions.
This module is also available for v10CE as well.
