### ISSUE TITLE
[10.0] web_one2many_kanban not ported yet?

### ISSUE THREAD

**Issue by afwanwh** [JayVora-SerpentCS/SerpentCS_Contributions-v8#68]
I installed web_one2many_kanban on my odoo 10 enterprise.But it didn't work like in v9. Is it not ported yet?

If yes, when you will finsih porting this module?

Thank you.

**Comment by sudhir-serpentcs** [comment]
@afwanwh thanks for your interest in the module and for the comment.
We have migrated the module in v10 and it will work both in community and in enterprise versions.

**Comment by afwanwh** [comment]
Hai @sudhir-serpentcs , your module is working great. Thanks to you and SerpentCS. 

However, I found two issues on enterprise. (For the moment I put the issues here. If you wish to open new issue, it will be OK for me)
1. Kanban size seems not fit to the stage size.
![issue2](https://cloud.githubusercontent.com/assets/8463442/21796678/dbe8da6e-d73c-11e6-9a9f-be0066f73d5d.PNG)

2. There is blank space (area with red line)
![issue1](https://cloud.githubusercontent.com/assets/8463442/21796697/fb93be42-d73c-11e6-83c8-9d52d64555b7.PNG)
