### ISSUE TITLE
Is it working in Odoo 8?

### ISSUE THREAD

**Issue by Softdil** [JayVora-SerpentCS/SerpentCS_Contributions-v8#7]
Hi, is the signature module working actually in Odoo 8?

How could I make it work in Odoo 8? Thanks

**Comment by JayVora-SerpentCS** [comment]
yes! Will give you the link soon.

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8
