### ISSUE TITLE
odoo 9.0 - mass label printing module error

### ISSUE THREAD

**Issue by odaybari** [JayVora-SerpentCS/SerpentCS_Contributions-v8#75]
Hi
I am finding follwing error when installing the label module.

`
 /odoo/custom/addons/label/__init__.py", line 4, in <module>
    from . import models
ImportError: cannot import name models`

Please help.

**Comment by JayVora-SerpentCS** [comment]
Did you face this in v9?

**Comment by odaybari** [comment]
yes. it is in odoo v9

I have tested on different ubuntu install. also getting this if i change `from . import model` to `import model`

`File "/odoo/custom/addons/label/report/dynamic_label.py", line 15, in <module>
    import utils
ImportError: No module named utils`

**Comment by JayVora-SerpentCS** [comment]
Please check with the latest module : https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/tree/9.0/label
For utils and cairo, you need to install libraries.

**Comment by odaybari** [comment]
JayVora-SerpentCS thank you for your help.

I have installed python-utils package using pip install and I am still getting utils importError for utils.
any idea why?

also there is error for `_logger.info ()`

**Comment by odaybari** [comment]
my bad, I have installed the wrong libraries. I have seen that you have provided solution in https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/issues/25

following package are required.
sudo pip install pyBarcode
sudo pip install utils
sudo pip install cairosvg

Thanks again Jayvora.

**Comment by JayVora-SerpentCS** [comment]
Perfect, thanks!
