### ISSUE TITLE
How to add loss of product processing in odoo manufacturing order also work order?

### ISSUE THREAD

**Issue by LakshminarayananOKN** [JayVora-SerpentCS/SerpentCS_Contributions-v8#76]
i am currently working in odoo 10 module manufacture, now i want to add product processing loss in BOM and Also manufacture order,work order and calculate product processing loss percentage :

for example: creating manufacturing order for 100kg yarn for dying process, while it return with processing loss like 2% or more like that, so i receive 98kg of dyed yarn so i want to calculate and add in stock BOM product

i know serpent know well serpent about odoo

**Comment by JayVora-SerpentCS** [comment]
You can manage this by % accuracy at each workcenter.
