### ISSUE TITLE
Error: QWeb2: Template 'ListView.row.image' not found

### ISSUE THREAD

**Issue by JasonCanaan** [JayVora-SerpentCS/SerpentCS_Contributions-v8#77]
On a clean Odoo 10.0, installing "web_tree_image" and then "sales_report_product_image", generates below error when filling in sales quotation:

> Traceback:
> Error: QWeb2: Template 'ListView.row.image' not found
>     at Object.exception (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2908:7)
>     at Engine._render (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2952:103)
>     at Engine.render (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2948:151)
>     at Class.format (http://localhost:8069/web/content/334-afc8657/web.assets_backend.js:3213:13)
>     at Class.render_cell (http://localhost:8069/web/content/334-afc8657/web.assets_backend.js:2070:15)
>     at Object.render_cell (http://localhost:8069/web/content/334-afc8657/web.assets_backend.js:2075:887)
>     at eval (eval at _render (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2949:73), <anonymous>:59:30)
>     at Object.foreach (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2919:18)
>     at Engine.eval (eval at _render (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2949:73), <anonymous>:45:23)
>     at Engine._render (http://localhost:8069/web/content/251-b10c2cd/web.assets_common.js:2948:296)

Uninstalling the module also causes Odoo to break
![image](https://cloud.githubusercontent.com/assets/25490998/22525123/05685a96-e894-11e6-8aeb-0e41212ea5eb.png)

**Comment by sudhir-serpentcs** [comment]
Hello @JasonCanaan 
We tried to generate the same error but it worked fine.
We installed the said modules and created the sales quotation. The images show up in the sales line and in the report as well.
Would you please let us know what is the version of base code v10c?

Thanks for your support.
