### ISSUE TITLE
Multi-DB Synchronization odoo 10

### ISSUE THREAD

**Issue by abdo-email** [JayVora-SerpentCS/SerpentCS_Contributions-v8#78]
pooler is no found in odoo 10, so that line is no executed and the module is no working on odoo 10

from openerp import pooler

in base_synchro\wizard\base_synchro.py

**Comment by chrislundholm** [comment]
following this, having same issue

**Comment by JayVora-SerpentCS** [comment]
We have fixed this with the recent push. Please check and update if you still face the issue.
Thanks.
