### ISSUE TITLE
[9.0] Label : missing fields in labels near end of printout

### ISSUE THREAD

**Issue by debaetsr** [JayVora-SerpentCS/SerpentCS_Contributions-v8#79]
Situation : create an address label with name, street, zip & city
Label printed : others, 21 labels /  page
Result : missing fields near 75% of the the result followed by empty pages.

The issue seems to be in report/dynamic_label.py, line 101:
`for row in range(0,len(result)/(columns +1)):
`
Replacing with  
`for row in range(0,(len(result)/columns)+1):`

seems to do the trick at least for the afore mentioned layout.

**Comment by JayVora-SerpentCS** [comment]
@debaetsr we will check and respond back.

**Comment by JayVora-SerpentCS** [comment]
Would you please tell us what is the config page format you use?
Usually, this works fine and hence I am closing it. Once we have info, we will reopen.
