### ISSUE TITLE
mass label reporting module Odoo v8

### ISSUE THREAD

**Issue by tbuonanno** [JayVora-SerpentCS/SerpentCS_Contributions-v8#80]
I'm using the "mass label reporting" module - odoo v8. The module works ok. When printing labels is not displayed barcode in pdf file. Other fields (image and characters are ok).

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/pull/85 fixed this.
