### ISSUE TITLE
[8.0 - base_module_record]  RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by livingmine** [JayVora-SerpentCS/SerpentCS_Contributions-v8#82]
This is a supposedly very valuable module but i can't seem to get it working.

Steps to reproduce:
* Create one product
* Launch export customisation as a module
* Keep the list of models shown by default
* Add product.template model to the list of models
* If "YAML" is ticked and "Record" button is pressed then "maximum recursion depth exceeded" is raised
* Else
  * Press "Record" button and fill mandatory fields in the popped wizard
  * Press "Continue"
* "maximum recursion depth exceeded" is raised

Extra information:

1. This might be related to issue #29 
2. If i choose another model for example res.partner, everything is working just fine.

**Comment by JayVora-SerpentCS** [comment]
@livingmine we will take a look and recheck.

**Comment by JayVora-SerpentCS** [comment]
#90  closed it.

**Comment by livingmine** [comment]
Thanks!
Exporting 'product.template' to XML now works fine, but exporting it to YAML raises `Error 'product_tmpl_id'`. However, exporting 'product.product' to YAML also works just fine.

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS please take a look.
