### ISSUE TITLE
[v10] error while installing "Project Dates on Kanban"

### ISSUE THREAD

**Issue by m3dbedb** [JayVora-SerpentCS/SerpentCS_Contributions-v8#84]
ParseError: "Error while validating constraint

\u042d\u043b\u0435\u043c\u0435\u043d\u0442 '<field name="task_ids">' \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u043d\u0430\u0445\u043e\u0434\u0438\u0442\u0441\u044f \u0432 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u043e\u043c \u0432\u0438\u0434\u0435

\u041e\u0448\u0438\u0431\u043a\u0430 \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u0430:
\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 `project.kanban.view.kanban`
[view_id: 579, xml_id: \u041d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e, model: project.project, parent_id: 561]
None" while parsing file:///c:/Program%20Files%20(x86)/Odoo%2010.0/server/custom/project_kanban/views/project_kanban_view.xml:17, near
<record id="project_kanaban_view_kanban" model="ir.ui.view">

**Comment by JayVora-SerpentCS** [comment]
@m3dbedb We are checking soon.
Thanks.

**Comment by JayVora-SerpentCS** [comment]
Dear, this does not happen. Please check latest release. What other modules have you installed?
