### ISSUE TITLE
Categories menu

### ISSUE THREAD

**Issue by yyuri** [JayVora-SerpentCS/SerpentCS_Contributions-v8#9]
I find that when you access to some product_brand, via website, and you click in some product category it will show again all products from all brands, and not only the brand that the user chose before.

Are you thinking in work on that?
We're so interested on it.
Many thanks!

**Comment by JayVora-SerpentCS** [comment]
@yyuri, We will take a look asap and update you.
Thanks.

**Comment by yyuri** [comment]
Nice, really thanks!

**Comment by JayVora-SerpentCS** [comment]
Closed by https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/commit/0820d371f040eb8c4b8283dc2edda435f516dfdb
