### ISSUE TITLE
Multi-db Sync issue when syncing products and varients (Odoo 10 Community)

### ISSUE THREAD

**Issue by ffadaei** [JayVora-SerpentCS/SerpentCS_Contributions-v8#95]
Greetings, and thanks in advance for your assistance.

I am using the latest builds of Odoo 10 and Multi-DB Synchro to sync about 1000 product templates between one DB running on Odoo 10 Enterprise and one DB on Odoo Community

I am getting the following traceback error when I attempt to sync the product.template object  I also get an error when I attempt to sync product.product, but other objects (categories and attributes) imported without error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/ExtraAddons/base_synchro/wizard/base_synchro.py", line 302, in upload_download_multi_thread
    threading.Thread(target=self.upload_download())
  File "/usr/ExtraAddons/base_synchro/wizard/base_synchro.py", line 265, in upload_download
    self.synchronize(server, obj_rec)
  File "/usr/ExtraAddons/base_synchro/wizard/base_synchro.py", line 110, in synchronize
    fields)[0]
  File "/usr/ExtraAddons/base_synchro/wizard/base_synchro.py", line 34, in <lambda>
    *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault object unbound: 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 56, in xmlrpc_return\n    result = odoo.http.dispatch_rpc(service, method, params)\n  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 118, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 38, in dispatch\n    res = fn(db, uid, *params)\n  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper\n    return f(dbname, *args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 182, in execute\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\n  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 171, in execute_cr\n    return odoo.api.call_kw(recs, method, args, kw)\n  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3007, in read\n    values[name] = field.convert_to_read(record[name], record, use_name_get)\n  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5186, in __getitem__\n    return self._fields[key].__get__(self, type(self))\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 869, in __get__\n    self.determine_value(record)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 980, in determine_value\n    self.compute_value(recs)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 935, in compute_value\n    self._compute_value(records)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 926, in _compute_value\n    getattr(records, self.compute)()\n  File "/usr/lib/python2.7/dist-packages/odoo/addons/website_sale/models/product.py", line 147, in _website_price\n    p.website_price = p.product_variant_id.website_price\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 869, in __get__\n    self.determine_value(record)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 980, in determine_value\n    self.compute_value(recs)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 935, in compute_value\n    self._compute_value(records)\n  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 926, in _compute_value\n    getattr(records, self.compute)()\n  File "/usr/lib/python2.7/dist-packages/odoo/addons/website_sale/models/product.py", line 193, in _website_price\n    pricelist = self.env[\'website\'].get_current_website().get_current_pricelist()\n  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/website.py", line 395, in get_current_website\n    domain_name = request.httprequest.environ.get(\'HTTP_HOST\', \'\').split(\':\')[0]\n  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 338, in __getattr__\n    return getattr(self._get_current_object(), name)\n  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 297, in _get_current_object\n    return self.__local()\n  File "/usr/lib/python2.7/dist-packages/werkzeug/local.py", line 132, in _lookup\n    raise RuntimeError(\'object unbound\')\nRuntimeError: object unbound\n'>

**Comment by JayVora-SerpentCS** [comment]
Would you please share the configuration?

**Comment by ffadaei** [comment]
not sure what you are asking for specifically??

**Comment by ffadaei** [comment]
I have two Ubuntu servers... one is running Odoo10 Enterprise (this is the source of the data)
One server is running Odoo10 Community (this is the destination of the data)...Both are in multi-db mode and both have working SSL certs installed...

I am attempting to sync all of the products, images, variants, attributes, etc, and the partners.

I am syncing from the destination server.  I was able to sync attributes, and categories with no problem, but having trouble with the product templates and product variants.... 

It may have something to do with the number of records in these tables since I have approx 1000 product templates and 90k product varients... but even when I set the domain to [('id','<',10)] I get this error.




![image](https://cloud.githubusercontent.com/assets/9721960/25326879/9dfb9384-2897-11e7-843c-e592526ac497.png)

![image](https://cloud.githubusercontent.com/assets/9721960/25328137/5b5e6056-289c-11e7-95f8-9e8e1d4d6ef1.png)


URLs:
Source: https://thevapebar.com 
Destination: https://okc.thevapebar.com

**Comment by ffadaei** [comment]
Please tell me if you need to see other configuration settings...  I can create a login for you if you need.

Thanks

**Comment by sudhir-serpentcs** [comment]
@ffadaei we have checked out the same config and we did not face any issue. we doubt the problem could be any 3rd party app. Even the error does not point to anything on module, it points for more web modules code, precisely something to do with website_sale. We will post our config soon.

**Comment by sudhir-serpentcs** [comment]
@ffadaei  
 Configure Servers: is running Odoo10 Enterprise
 
![server](https://cloud.githubusercontent.com/assets/13166978/25382829/e6c50920-29d6-11e7-9889-daf647b2e53a.png)

Configuration the object for synchronization:  Upload/Download data or both simultaneously. 

![confi](https://cloud.githubusercontent.com/assets/13166978/25382873/201e4dd0-29d7-11e7-8520-13d7ec2f3f08.png)

Synchronization:
![syn](https://cloud.githubusercontent.com/assets/13166978/25383009/a5be5aac-29d7-11e7-8511-6fe724d2f1a0.png)

Get Product in other server is running Odoo10 Community 

![pro](https://cloud.githubusercontent.com/assets/13166978/25383084/13536fc6-29d8-11e7-8891-ae823a7a08ab.png)

Thank you.

**Comment by ffadaei** [comment]
I'm confused, does it mean that I need to exclude some fields? Or install another module?

**Comment by ffadaei** [comment]
also, I think I am doing the opposite as your sync is being initiated from the Enterprise server while my sync is being initiated from the community server... not sure if that would make a difference...

**Comment by ffadaei** [comment]
Please help me, I am stuck here! Where should I be looking?

**Comment by hpatelserpentcs** [comment]
@ffadaei 
You can synchronization both (community and enterprise) server no issue fetch. both side Upload/Download data or both simultaneously.  Only check both server same module installed or not.

**Comment by JayVora-SerpentCS** [comment]
We are closing this one for now! Do let me know if the problem appears.

**Comment by seragtarek** [comment]
I have same problem, i have the pos users on the community and products database and accounting on the enterprise.. need to know how to sync them.
